### ISSUE TITLE
Publish artifact at JCenter or Maven Central

### ISSUE THREAD

**Issue by vRallev** [firebase/firebase-jobdispatcher-android#1]
This makes using the library especially in other libraries a lot easier. Copying the `.aar` is not a good idea.

**Comment by ciarand** [comment]
Absolutely agree. We're working on getting an artifact posted ASAP.

**Comment by estsauver** [comment]
This may be better addressed in another issue, but is this library ready for production? There's a note on the GCMNetworkManager that it's been deprecated in favor of this, but is this ready for general use?

**Comment by kenyee** [comment]
Curious why this isn't on Maven Central as well?

IMHO, it should be part of the standard Firebase libraries though....not sure why it's been broken out here instead...

**Comment by Ab-Appletic** [comment]
Still nothing? GG firebase

**Comment by drmrbrewer** [comment]
+1 ... come on!

**Comment by gabrielittner** [comment]
@ciarand Could you also sync the artifacts to maven central (FirebaseUI does it too)?

**Comment by ciarand** [comment]
Created #68 to track that.
