### ISSUE TITLE
JobService not starting when using Parcelable extras

### ISSUE THREAD

**Issue by cascal** [firebase/firebase-jobdispatcher-android#100]
Hi all,

I have a `JobService` that seems to work perfectly fine until I add `Parcelable` extras. Here is the example code I'm using:

Note: `Books` is a POJO that implements the `Parcelable` interface.
```
ArrayList<Book> books = new ArrayList<>(getAllBooks());
        if (!books.isEmpty()) {
            Bundle extras = new Bundle();
            extras.putParcelableArrayList(SyncJobService.EXTRA_ALL_BOOKS, books);

            Job job = mJobDispatcher.newJobBuilder()
                    .setService(SyncJobService.class)
                    .setTag(SyncJobService.TAG)
                    .setConstraints(Constraint.ON_UNMETERED_NETWORK)
                    .setTrigger(Trigger.NOW)
                    .setLifetime(Lifetime.UNTIL_NEXT_BOOT)
                    .setRecurring(false)
                    .setExtras(extras)
                    .build();

            int result = mJobDispatcher.schedule(job);
            if (result != FirebaseJobDispatcher.SCHEDULE_RESULT_SUCCESS) {
                Log.d("ERROR", "could not schedule");
            }
```

my `AndroidManifest.xml` file:

```
...

<service android:name=".service.job.SyncJobService" android:exported="false">
    <intent-filter>
            <action android:name="com.firebase.jobdispatcher.ACTION_EXECUTE" />
    </intent-filter>
</service>
```

Oddly enough, the call to `FirebaseJobDispatcher#schedule` always returns `SCHEDULE_RESULT_SUCCESS`, but the service never actually runs. That is, `onStartJob` is never called for `SyncJobService`. If I remove the call to `FirebaseJobDispatcher#setExtras` or create a `Bundle` without any `Parcelable` extras, `onStartJob` **will** be called for my service.

**Comment by michaeldiener** [comment]
I'm curious, for what device with which Android version is this happening?

I'm investigating an issue for my own app that only happens for certain devices and like to see if there is a correlation.

**Comment by lisemon** [comment]
I am guessing that it is because the jobdispatcher cannot use a bundle with values that are parcelable. Has to be Integer, Long, Double, String, and Boolean, based on my experience.

**Comment by AndreiZaitcev** [comment]
That's true. I faced this issue too. More information on this here https://commonsware.com/blog/2016/07/22/be-careful-where-you-use-custom-parcelables.html. There is also a workaround in the end of the article. Seems to work fine for me.

**Comment by thiagocard** [comment]
Since Firebase JobDispatcher relies on Google Play Services, it can't know how to unmarshall your custom Parcelable... It uses a [PersistableBundle](https://developer.android.com/reference/android/os/PersistableBundle.html) which works only with some restricted types.

**Comment by tomasmichael995** [comment]
Also happened to me. I am using two Samsung galaxy devices. Here is a relevant issue :  https://stackoverflow.com/a/28589962

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
