### ISSUE TITLE
Need we call jobFinished() after job done on background thread

### ISSUE THREAD

**Issue by tantanbei** [firebase/firebase-jobdispatcher-android#106]
If I post a runnable on background to do some jobs , Need we call jobFinished() by manual after job done on background thread?

**Comment by unEgor** [comment]
Hi 
You need to call jobFinished() method when your job is completed. Other wise framework will think that the job failed with timeout and will try rerun it with a retry policy.

**Comment by tantanbei** [comment]
Thank you. And what is the correct way to call jobFinished() on a runnable. Need new MyJobService() and call it jobFinished() method. Or write an callback method when runnable is completed. Or runnable is inner class on MyJobService class

**Comment by tantanbei** [comment]
And I see the [DemoJobService](https://github.com/firebase/firebase-jobdispatcher-android/blob/master/testapp/src/main/java/com/firebase/jobdispatcher/testapp/DemoJobService.java), It is not call jobFinished() when job is completed. Why?

**Comment by unEgor** [comment]
Correct. DemoJobService does not need to call jobFinished because it returns false on onStartJob.
You should call jobFinished on the same instance of JobService otherwise it won't work.

**Comment by tantanbei** [comment]
@unEgor Thank you!
