### ISSUE TITLE
Testing schedules

### ISSUE THREAD

**Issue by ocampoleandro** [firebase/firebase-jobdispatcher-android#107]
Hello.
I would like to know if changing the system time manually is enough to test some task schedules. 
I have to set a schedule every 30 days and changing the time manually doesn't work to test it apparently. 

Thanks!

**Comment by unEgor** [comment]
Hello,

Changing system time is not enough to trigger your job.
You can test your job by setting smaller period. It will allow you to test your logic and that the task was scheduled correctly.

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
