### ISSUE TITLE
0.6.0: NullPointerException jobFinished

### ISSUE THREAD

**Issue by michaeldiener** [firebase/firebase-jobdispatcher-android#109]
In Firebase Crash Analytics I see the following exception:

java.lang.NullPointerException:
android.os.Message.sendToTarget (Message.java:360)
com.firebase.jobdispatcher.JobService$JobCallback.sendResult (JobService.java)
com.firebase.jobdispatcher.JobService.jobFinished (JobService.java)
MyJob.run (MyJob.java)

Not sure this is caused by the jobdispatcher directly but in any case the job result cannot be send.

I see this happening for:
LG-E975 on 4.4.2
SM-G950F on 7.0

**Comment by unEgor** [comment]
Could you please check if https://github.com/firebase/firebase-jobdispatcher-android/pull/105 fixes the issue?

**Comment by michaeldiener** [comment]
Looking at the stacktrace of #104 it seems a different issue. 
Also, I'm not able to reproduce the issue myself, it only happens for 3 users in the wild for my live app. Will have to wait for the next jobdispatcher release before I test it.
