### ISSUE TITLE
job is still running even after cancel

### ISSUE THREAD

**Issue by Hardik-mehta** [firebase/firebase-jobdispatcher-android#110]
I have  made demo for requesting location updates using job but even after cancelling the job after some time interval it is restarting 

Device on which i am running this demo is Samsung Galaxy Core 2 
OS : 4.4

**Comment by unEgor** [comment]
How do you cancel the job?
Do you use periodic job?

**Comment by Hardik-mehta** [comment]
Yea it is for location updates so it is periodic and I cancel it in activity 's on destroy method by dispatcher.cancel("my job").

**Comment by unEgor** [comment]
Your job should be canceled in that case.
Are you sure that onDestroy was called?
You can check job status by "adb shell dumpsys activity service GcmService --endpoints YOUR_ENDPOINT"

**Comment by ash242186** [comment]
I am also facing same issue, yes jobservice called onDistroy

**Comment by IgorTorba** [comment]
I'm facing  with same issue. I'm starting periodic job like this
```java
 Job updateJob = jobDispatcher.newJobBuilder()
                .setService(UpdatesLocation.class)
                .addConstraint(Constraint.ON_ANY_NETWORK)
                .setTrigger(Trigger.executionWindow(0, 30))
            .setLifetime(Lifetime.FOREVER)
                .setRecurring(true)
                .setReplaceCurrent(true)
                .setTag(UpdatesLocation.JOB_TAG)
                .build();
        jobDispatcher.mustSchedule(updateJob);
```
After some time I trying to cancel job
```java
jobDispatcher.cancel((UpdatesLocation.JOB_TAG);
```

But when after some time later I'm trying to start job I got 
`W/FJD.JobService: Job with tag = com.bla-bla-mysuperpackage.UpdatesLocation was already running.`

I'm not getting ` onStartJob(JobParameters job)`

**Comment by IgorTorba** [comment]
```
    Pending:

    (scheduled) com.bla-bla-mysuperpackage/com.firebase.jobdispatcher.GooglePlayReceiver{u=0 tag="com.bla-bla-mysuperpackage.UpdatesLocation" trigger=window{start=0s,end=30s,earliest=-19s,latest=10s} requirements=[NET_CONNECTED] attributes=[PERSISTED,RECURRING] scheduled=-19s las
t_run=N/A jid=N/A status=PENDING retries=0}
    Not yet run.

    Past executions:

    (finished) [com.bla-bla-mysuperpackage/com.firebase.jobdispatcher.GooglePlayReceiver:com.bla-bla-mysuperpackage.UpdatesLocation,u0]
    successes: 0 reschedules: 0 failures: 0 timeouts: 110 invalid_service: 0 total_runtime_secs: 0
```
I canceled previous job and started new job, but got
 `W/FJD.JobService: Job with tag = com.bla-bla-mysuperpackage.UpdatesLocation was already running.`

Can someone clarify this behaviour?

**Comment by IgorTorba** [comment]
Found solution. Need to call ` jobFinished(job, false)` if you want to restart job manually and get `onStartJob(JobParameters job)` callback.

**Comment by unEgor** [comment]
Sorry for the late reply.
There is no guaranty that onDestroy will be called. 
https://developer.android.com/reference/android/app/Activity.html#onDestroy%28%29
https://stackoverflow.com/questions/4449955/activity-ondestroy-never-called

I'm closing the issue.
Feel free to reopen it and provide logs or some evidence that a job is executed after it was canceled.

**Comment by sylvain-toptal** [comment]
Thanks @IgorTorba I was under the impression that `jobFinished` needed to be called but nowhere is this documented!
