### ISSUE TITLE
scheduled Job every day 11:59 clock (night)

### ISSUE THREAD

**Issue by pravinsenta** [firebase/firebase-jobdispatcher-android#113]
hi 

in my app i want to close day at every day at 11:59  clock  (23:59) night, how to schedule  job for the this time interval.

**Comment by ogeidix** [comment]
Hi @pravinsenta,
the best place where to ask similar questions is www.stackoverflow.com.
In this way we can keep the issue tracker in github for Issues and Bug reports.

Thanks.
- Diego

**Comment by dmitrikudrenko** [comment]
@pravinsenta any solution?
