### ISSUE TITLE
GooglePlayReceiver continues to run after jobFinished called

### ISSUE THREAD

**Issue by rde8026** [firebase/firebase-jobdispatcher-android#114]
I'm seeing an issue with `firebase-jobdispatcher-with-gcm-dep:0.6.0 ` where jobs that are scheduled and completed (meaning `jobFinished(params, true)` is called after work completes) do not seemed to get stopped. After a job completes and I look at running services I see under my app the GooglePlayReceiver continues to run. This is an issue for a few reason, one I don't know why its still running and it seems to slowly take more memory as time goes on.

I've tested this with a few version of GooglePlayServices and I don't any changes. I've tried calling jobFinished on main thread and background threads, but the GooglePlayReceiver continues to run.

**Comment by unEgor** [comment]
Thank you for finding the issue.
I believe it is because we don't call "Service.stopSelf" in "GooglePlayReceiver.onJobFinished"

**Comment by rde8026** [comment]
Thanks @unEgor. Do you have a rough estimate of when this might get fixed?

**Comment by unEgor** [comment]
The fix will be ready soon.

**Comment by HenningBu** [comment]
Isn't this one closed? See commit: https://github.com/firebase/firebase-jobdispatcher-android/commit/2e37916cf0c771ef3e3d15f2a42a88938c2331c4
