### ISSUE TITLE
Make RetryStrategy customizable

### ISSUE THREAD

**Issue by bubenheimer** [firebase/firebase-jobdispatcher-android#115]
Please make RetryStrategy customizable. As far as I can tell, there are only two hard-coded retry strategies, and both end at a maximum backoff of 1 hour. In my app I need to retry longer than that, as the app is used away from WiFi, and in areas with commonly spotty cellular data coverage, where it may reasonably take much longer than 1 or 2 hours to get data coverage again - 12 hours is a much better maximum in my case. Retrying is needed to synchronize app state between several users, so if it does not happen, then app state is essentially screwed.

**Comment by bubenheimer** [comment]
Invalid. Halfway reasonable documentation would have helped.

**Comment by michaeldiener** [comment]
How did you manage to do it?

**Comment by michaeldiener** [comment]
Nevermind, I found it. If anybody else is looking for it, there is a method "newRetryStrategy" in the FirebaseJobDispatcher class..
