### ISSUE TITLE
getting data from database(eg Sqlite)

### ISSUE THREAD

**Issue by surindersinghbindra** [firebase/firebase-jobdispatcher-android#119]
if i want to send some data from database of my app. how i can get Context to open a connection with the database(To Get Readable Database)     
`public class MyJobService extends JobService {
    @Override
    public boolean onStartJob(JobParameters job) {
        // Do some work here
 DatabaseHelper datbasehelper= **context**.getReadableDatabase();
        return false; // Answers the question: "Is there still work going on?"
    }

    @Override
    public boolean onStopJob(JobParameters job) {
        return false; // Answers the question: "Should this job be retried?"
    }
}`

**Comment by FabianTerhorst** [comment]
The JobService is extending Context so you can use the service itself as an context.
