### ISSUE TITLE
Job does not get triggered for some Samsung devices running Android 7

### ISSUE THREAD

**Issue by michaeldiener** [firebase/firebase-jobdispatcher-android#120]
I use the scheduling in my app and in general it works fine. There are some users reporting issues and there seems to be a pattern in their devices:
SM-G930F (Android 7.0)
SM-G920P (Android 7.0)

The scheduling is started without any exception but the job never gets triggered. Here's the code:

```
FirebaseJobDispatcher dispatcher = new FirebaseJobDispatcher(new GooglePlayDriver(context));

Job myJob = dispatcher.newJobBuilder()
		.setService(CheckBackgroundJobService.class)
		.setTag("xxx_" + myId)
		.setRecurring(false)
		.setLifetime(Lifetime.FOREVER)
		.setTrigger(shouldTriggerNow ? Trigger.NOW : Trigger.executionWindow(0, 60))
		.setReplaceCurrent(true)
		.setRetryStrategy(RetryStrategy.DEFAULT_EXPONENTIAL)
		.setConstraints(Constraint.ON_ANY_NETWORK)
		.setExtras(myExtrasBundle)
		.build();

dispatcher.mustSchedule(myJob);
```

Let me know if you need more information.

**Comment by asafkin** [comment]
Happens on SM-G950F as well.

This is happening because the Power Saving mode is on. Once you switch it off everything works. 
Still this is an issue needs to be addressed.

**Comment by michaeldiener** [comment]
I've talked to 2 users having the issue. One is using the power saving mode, the other is not.

Also now that I monitor the scheduling in Firebase Analytics I see more devices and Android versions being affected. Still rolling out my new version with this monitoring enabled and will be able to tell more in a few days.

**Comment by michaeldiener** [comment]
After gathering some statistics in Firebase Analytics I can see that the problem happens for 1.5% of my users amounting to a few thousand. There are also other devices than Samsung concerned as well as other Android versions: 7.0 - 54.4%, 6.0.1 - 26.3%, 5.1.1 - 7.8%, Other - 11.5%

In the next release of my app (in 1-2 weeks) I'll add monitoring of the power save state for Android >= 21.
Any suggestion on what other properties to monitor to better investigate this issue?

**Comment by unEgor** [comment]
You could check if your app was force stopped. In that case jobs won't run until user opens it.

**Comment by crashless** [comment]
Any further information on this issue? I'm seeing it on the G920V with android 7. However it works correctly on the G955U which is also running 7.

**Comment by GuillaumeLachaud** [comment]
Seeing this exclusively on Samsung devices:
SM-G935A running 7.0
SM-N920V running 7.0
SM-J120AZ running 6.0.1
SM-J700T running 7.0
SM-G935T running 7.0.1
Charging state of the device don't seem to be the cause as some of them are plugged, some are not. 

Locally, I have been able to reproduce on a SM-G935T running 7.0.1. Jobs are not running until Power Saving Mode is turned off. Turning off power saving mode makes the queued jobs running instantly.

Using 

> adb shell dumpsys activity service GcmService --endpoints myapp

I can see that the jobs are indeed scheduled correctly but are not firing:


```
(scheduled) package/TaskService{u=0 tag="tag" trigger=window{period=600s,flex=60s,earliest=-240s,latest=-180s} requirements=[NET_CONNECTED] attributes=[PERSISTED,RECURRING] scheduled=-780s last_run=N/A jid=N/A status=READY retries=0}
    Not yet run.

    Past executions:
```

Looking at the Power Saving Mode description, it clearly turns off background networking, probably meaning it is indefinitely delaying jobs.

![device-2017-09-15-110446](https://user-images.githubusercontent.com/2076017/30496932-d17d50aa-9a05-11e7-9045-ce88cffd045d.png)

Unfortunately, unlike Doze or App Standby that are turned off as soon as the user interacts with the device or the app, this imitation will keep operating even if your app is in the foreground and the user is interacting with it. 

There's a little bit of literature on stackoverflow regarding this Samsung Power saving mode but no clean API to detect whether it is on or how to work around it.

**Comment by ChristopheVersieux** [comment]
I can confirm this issue.
As there is no fail callback in the Job , have you found a way to programmatically identify the guilty devices to provide an alternate sync method in such cases?

**Comment by michaeldiener** [comment]
I have been monitoring the scheduler as well as the power save state now for a bit.
6% of users have issues with scheduling - seems quite high. Only 3.5% of all users enabled the power save state.

My workaround is to check after a certain time if the job really ran by using the good old AlarmManager. If scheduling did not work, I fall back completely to AlarmManager. Not really nice, but does the job.

**Comment by crashless** [comment]
Is it possible that a switch just got flipped somewhere? One of my alpha testers that was having this issue just reported that my app suddenly came to life this afternoon. Is this an isolated case?

**Comment by yma44** [comment]
I see this case has been raised a while ago.  This has not been fixed, has it? My jobs constraint uses Constraint.ON_ANY_NETWORK as well and if a device is on battery saver mode, the job won't run.  It happens on not only Samsung but all devices. Is this issue going to be addressed soon?

**Comment by michaeldiener** [comment]
You might want to switch to [WorkManager](https://developer.android.com/topic/libraries/architecture/workmanager). 

WorkManager is part of the official Android Jetpack and actively maintained, not like this library here. As a matter of fact they have finally released the first stable version 1.0 this week after about 10 months of public alpha and beta. It's now much more stable than Firebase Jobsdispatcher ever was...

**Comment by crashless** [comment]
I too have abandoned use of this - which was frustrating because Google had specifically said "Firebase Jobdispatcher is the future!!!". Whelp...tech marches on.

**Comment by EKoetsjarjan** [comment]
Hi I have the same issue with some samsung devices. 
I'm using FirebaseJobDispatcher, did someone tried the workmanger ? it seems also to use jobscheduler which FirebaseJobDispatcher also uses. why should it be more stable then?

**Comment by TayfunCesur** [comment]
I had the same issue, then I tried the work manager but at that time I faced the same issue,
My device was Samsung s8 (Android 9) and I always use power save mode, so my works didn't trigger at exact time,
so I found ,
[https://stackoverflow.com/questions/50546739/is-workermanager-a-realiable-way-to-implement-alarm-reminder-feature-in-the-app](this answer)
then I decided to go forward to AlarmManagerCompat
Now the problem is gone. My works trigger at the exact time even if device is power save mode

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
