### ISSUE TITLE
own Exception java.lang.NoSuchMethodError: com.google.android.gms.gcm.PendingCallback.getIBinder 

### ISSUE THREAD

**Issue by polivmi1** [firebase/firebase-jobdispatcher-android#121]
I keep receiving this exception with the latest firebase Jobdispatcher. I have a dependency on gcm:
    compile "com.google.android.gms:play-services-gcm:11.0.1"
    compile 'com.firebase:firebase-jobdispatcher-with-gcm-dep:0.6.0'

and this is the complete exception:
Exception java.lang.NoSuchMethodError: com.google.android.gms.gcm.PendingCallback.getIBinder
com.firebase.jobdispatcher.GooglePlayCallbackExtractor.extractCallback (GooglePlayCallbackExtractor.java:48)
com.firebase.jobdispatcher.GooglePlayReceiver.prepareJob (GooglePlayReceiver.java:159)
com.firebase.jobdispatcher.GooglePlayReceiver.onStartCommand (GooglePlayReceiver.java:98)
android.app.ActivityThread.handleServiceArgs (ActivityThread.java:2860)
android.app.ActivityThread.access$2200 (ActivityThread.java:161)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1362)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:157)
android.app.ActivityThread.main (ActivityThread.java:5356)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1265)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1081)
dalvik.system.NativeStart.main (NativeStart.java)

**Comment by FabianTerhorst** [comment]
play services 11.x.x aren´t supported right now.

**Comment by ogeidix** [comment]
This should be fixed with the new 0.7 release.
Please reopen if the problem persists.
