### ISSUE TITLE
Unable to instantiate service com.firebase.jobdispatcher.GooglePlayReceiver

### ISSUE THREAD

**Issue by KlGleb** [firebase/firebase-jobdispatcher-android#122]
My application occasionally crashes with that exception:

Fatal Exception: java.lang.RuntimeException
Unable to instantiate service com.firebase.jobdispatcher.GooglePlayReceiver: java.lang.ClassNotFoundException: Didn't find class "com.firebase.jobdispatcher.GooglePlayReceiver" on path: DexPathList[[zip file "/data/app/my.package.name-1/base.apk"],nativeLibraryDirectories=[/data/app/my.package.name-1/lib/arm, /vendor/lib, /system/lib]]
 

> Fatal Exception: java.lang.RuntimeException: Unable to instantiate service com.firebase.jobdispatcher.GooglePlayReceiver: java.lang.ClassNotFoundException: Didn't find class "com.firebase.jobdispatcher.GooglePlayReceiver" on path: DexPathList[[zip file "/data/app/ru.appspress.showcase-1/base.apk"],nativeLibraryDirectories=[/data/app/ru.appspress.showcase-1/lib/arm, /vendor/lib, /system/lib]]
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3047)
       at android.app.ActivityThread.-wrap4(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1571)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5728)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
Caused by java.lang.ClassNotFoundException: Didn't find class "com.firebase.jobdispatcher.GooglePlayReceiver" on path: DexPathList[[zip file "/data/app/ru.appspress.showcase-1/base.apk"],nativeLibraryDirectories=[/data/app/ru.appspress.showcase-1/lib/arm, /vendor/lib, /system/lib]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3044)
       at android.app.ActivityThread.-wrap4(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1571)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5728)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

Note: I use proguard, also  "persistent" flag in Manifest.xml switched on.

I haven't found a solution yet.  Could you help me, please?

**Comment by KlGleb** [comment]
I found  a description of a  similar  problem  in other library android-job [here](https://github.com/evernote/android-job/blob/master/FAQ.md#how-can-i-remove-the-gcm-dependency-from-my-app).  As I understand, it means that it can be a problem with GCM dependency. But.. I have this dependency everywhere. 

This exception have been starting after update one version to another. Both of them have JobDispatcher and GCM dependency like this:

` compile 'com.google.android.gms:play-services-gcm:10.2.6'
compile ("com.firebase:firebase-jobdispatcher-with-gcm-dep:0.6.0") {
        exclude module: "play-services-gcm"
    }
`

Exception is in the first version only. I mean that after updating the old version to new version exception was in the old version (as I understand, the old version сan hang because "persistent" flag switched on). But I don't understand how  I can solve the problem

**Comment by unEgor** [comment]
Hi Gleb,

Please use new version of Firebase Job Dispatcher.
Your problem was solved by excluding PendingCallback from the SDK.

compile 'com.firebase:firebase-jobdispatcher:0.7.0'

Thanks,
Egor

**Comment by KlGleb** [comment]
Hi, Egor!

I have a question: 

```
It's been a long time, and the problem was solved in most cases, but on some devices it's left:
Fatal Exception: java.lang.RuntimeException
Unable to instantiate service com.firebase.jobdispatcher.GooglePlayReceiver: java.lang.ClassNotFoundException: Didn't find class "com.firebase.jobdispatcher.GooglePlayReceiver" on path: DexPathList[[zip file "/system/priv-app/BQ_appspress_v7.2.6bq_Appspress-release/BQ_appspress_v7.2.6bq_Appspress-release.apk"],nativeLibraryDirectories=[/system/priv-app/BQ_appspress_v7.2.6bq_Appspress-release/lib/arm, /system/lib, /vendor/lib, /system/vendor/lib]]
```
Version 7.2.6 (I mean BQ_appspress_v7.2.6bq_Appspress) doesn't contains JobDispatcher library.

As I understand, It  can happen on specific devices after updating application (because persistent flag or something else).  After updating the old process left and it happens when the new process tries to find GooglePlayReceiver in the old. Is there a way  not show this error to user?

**Comment by unEgor** [comment]
Hi Gleb,

I think you could try to load the class by Class.forName(className) before use of FJD and if it throws ClassNotFoundException avoid FJD.

**Comment by KlGleb** [comment]
Egor, thank you!  

But I think that it's cannot solve the problem, because class not found in the old apk.  Is there a way not show this error to user -- something like tools:node="remove"  (I mean the example [here](https://github.com/evernote/android-job/blob/master/FAQ.md#how-can-i-remove-the-gcm-dependency-from-my-app)), but not remove?

**Comment by unEgor** [comment]
Hi Gleb,

Sorry I misunderstood the issue.
The class not found exception is caused by the system because of an inconsistency between the manifest service configuration and the process. So you can't check it.
When your install new version of the app where you first introduce FJD, I expect that no FJD jobs will be presented. So Goople Play Services can't try to start com.firebase.jobdispatcher.GooglePlayReceiver service.
I think your apk might be built incorrectly.

Could you check that your apk contains com.firebase.jobdispatcher.GooglePlayReceiver with apktool aapt?

**Comment by unEgor** [comment]
Also please verify that it is located in the right path.
[[zip file "/data/app/my.package.name-1/base.apk"],nativeLibraryDirectories=[/data/app/my.package.name-1/lib/arm, /vendor/lib, /system/lib]]

**Comment by unEgor** [comment]
I used "dexdump classes.dex | grep -A 10 -B 10 'GooglePlayReceiver'"

dexdump is in SDK

**Comment by unEgor** [comment]
https://stackoverflow.com/questions/10569015/unable-to-instantiate-service-classnotfoundexception
might also help

**Comment by KlGleb** [comment]
Egor,  thanks so much!

As I think, my problem is not exactly in FJD, but I need your help for solve this :-)

Apk built correctly, dexdump is [here](https://gist.github.com/KlGleb/8151c497d2024ad102bc0977ecb6df4d) .

And it can be located in system path, like /system/app/Appspress/  . 

We can see how both --  the old and the new processes  -- work simultaneously in some cases after update application.  It's only in specific devices.  (Note: ["Persistent" flag](https://developer.android.com/guide/topics/manifest/application-element.html) in Manifest.xml is switched on.  )   So, I am searching a way to use FJD in a compatible way with the apk that doesn't contains FJD and the receiver.

Maybe I should stop using com.firebase.jobdispatcher.GooglePlayReceiver ?  Is it a class for using GcmNetworkManager, can I switch off this and how can I do this?

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
