### ISSUE TITLE
setTrigger(Trigger.executionWindow(5, 10)) does not works. Gives triggering every ~30 sec, not between 5 and 10 on Android 6. (Samsung)

### ISSUE THREAD

**Issue by DmitriyYakovlev** [firebase/firebase-jobdispatcher-android#124]
Job myJob = dispatcher.newJobBuilder()
                .setService(KeepAliveJobService.class)
                .setTag(TG_KEEPER_JOB)
                .setRecurring(false)
                .setLifetime(Lifetime.FOREVER)
                .setTrigger(Trigger.executionWindow(5, 10))
                .setReplaceCurrent(true)
                .setRetryStrategy(RetryStrategy.DEFAULT_LINEAR)
                .build();

        dispatcher.mustSchedule(myJob);

**Comment by unEgor** [comment]
Hi Dmitriy,

Currently minimum delay for a job is 30 second. We plan to allow immediate execution with some restriction in near future. Unfortunately the problem can't be solved right now.

Thanks,
Egor

**Comment by DmitriyYakovlev** [comment]
Hi Egor,
I will take this to account.
Thanks for response.
