### ISSUE TITLE
JobSchedule check

### ISSUE THREAD

**Issue by darshan0071990** [firebase/firebase-jobdispatcher-android#125]
Hello, Is there any check to confirm if the Job is scheduled or not? 
eg: dispatcher.isScheduled(TAG);

**Comment by unEgor** [comment]
Hi Darshan,

Unfortunately there is not such check.
However we plan to implement the this in the future.

For now you can use "adb shell dumpsys activity service GcmService --endpoints YOUR_SERVICE".
You should not rely on the output because in will change in the future.

Thanks,
Egor
