### ISSUE TITLE
Are there any disadvantages of specifying the same value for the windowStart and windowEnd parameters in ExecutionWindowTrigger?

### ISSUE THREAD

**Issue by adil-hussain-84** [firebase/firebase-jobdispatcher-android#128]
I have a `Job` which I want to be triggered approximately every 24 hours. It's not a time-critical operation so does not have to be triggered exactly every 24 hours. I'm currently creating and scheduling this `Job` as follows:

    int twentyFourHours = 24 * 60 * 60;

    Job job = firebaseJobDispatcher.newJobBuilder()
        .setConstraints(Constraint.ON_ANY_NETWORK)
        .setLifetime(Lifetime.FOREVER)
        .setRecurring(true)
        .setReplaceCurrent(true)
        .setRetryStrategy(RetryStrategy.DEFAULT_EXPONENTIAL)
        .setService(SomeJobService.class)
        .setTag("SomeTag")
        .setTrigger(Trigger.executionWindow(twentyFourHours, twentyFourHours))
        .build();

    int scheduleResult = firebaseJobDispatcher.schedule(job);

My understanding of the `windowStart` and `windowEnd` parameters in `ExecutionWindowTrigger` is that these are approximate values for when the `Job` will trigger. So is there any disadvantage of specifying the same value for these two parameters or am I better specifying different values for these two parameters? If the latter, what would be sensible values for these two parameters for a `Job` that is to be triggered _roughly_ every 24 hours?

**Comment by blackhawk389** [comment]
I also did the same I wanted to trigger job exactly the time specified not between start and end, but job is triggering once, what about you,

**Comment by adil-hussain-84** [comment]
@blackhawk389: It is recurring for me, i.e. running every 24 hours. Be sure to call `setRecurring(true)` when building your job.

Also, be careful if you're calling `setReplaceCurrent(true)` when building your job. I'm not 100% sure about what this method does but from a bit of experimentation it looks like it reschedules your job. So, for example, if you had called `firebaseJobDispatcher.schedule(job)` at 9pm with `setReplaceCurrent(true)` and a execution window of every 24 hours then your job will trigger roughly at 9pm every day. If however, you were to call `firebaseJobDispatcher.schedule(job)` again at 10pm, then the job would no longer trigger at 9pm every day but instead at 10pm.

**Comment by blackhawk389** [comment]
Have a look https://github.com/firebase/firebase-jobdispatcher-android/issues/131

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
