### ISSUE TITLE
Questions about the capabilities of JobDispatcher

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [firebase/firebase-jobdispatcher-android#13]
I'd like to know what are the capabilities of it, so I created a StackOverflow post for it:
http://stackoverflow.com/q/37720015/878126

**Comment by eriuzo** [comment]
yes , especially please clarify (or add a section) on how to make recurring jobs

**Comment by samtstern** [comment]
Looks like @ciarand fixed this issue a long time ago, so closing.  Feel free to file follow-up issues about documentation.
