### ISSUE TITLE
Not run job in Service

### ISSUE THREAD

**Issue by LionZXY** [firebase/firebase-jobdispatcher-android#130]
Hello. I try using JobSchedulers for my chat app (for async send message):
```
 val job = dispatcher.newJobBuilder()
                .setService(BackgroundJobService::class.java)
                .setTag(BackgroundJobService.TASKTAG_SEND_MESSAGE)
                .setReplaceCurrent(false)
                .setConstraints(Constraint.ON_ANY_NETWORK)
                .setExtras(bundle)
                .setTrigger(Trigger.executionWindow(0, 1))
                .build()
dispatcher.mustSchedule(job)
```
And add my service in manifest:
```
<service
            android:exported="false"
            android:name=".data.background.service.BackgroundJobService">
            <intent-filter>
                <action android:name="com.firebase.jobdispatcher.ACTION_EXECUTE"/>
            </intent-filter>
</service>
```
```
class BackgroundJobService : JobService() {
    companion object {
        val TASKTAG_SEND_MESSAGE = "send_message"
        val EXTRA_MESSAGE = "message"
    }

    @Inject
    lateinit var webSocket: IRxWebSocket
    var subscribe: Disposable? = null

    override fun onCreate() {
        super.onCreate()
        App.appComponent.inject(this)
        subscribe = webSocket.connect().subscribe({}, {})
    }

    override fun onStartJob(job: JobParameters?): Boolean {
        return true // Debug point here
    }

    override fun onStopJob(job: JobParameters?): Boolean {
        return true
    }

    override fun onDestroy() {
        super.onDestroy()
        subscribe?.dispose()
    }
}
```

But my onStartJob not calling! Where is my mistake?

**Comment by MikhailSolncev** [comment]
Debug doesn't stop in service job. Job also didn't log anything by Log.d() or Log.e().
Put some notification or any other kind of checking that your program was there.

You return true in "onStartJob", but if you want to reschedule, you must return false. It must be answer the question  "Is there still work going on?"

**Comment by ZorOuyang** [comment]
Me too, and setTrigger never gets on time.

**Comment by MikhailSolncev** [comment]
Debug is not available in service. Log.d also not working.
In your onStratJob you returning "true", but you should answer the question "Does it still work?", so you have to return false. Otherwise it wouldn't be run second time.
Also a had trouble with DI in service and got NPE after injecting service. I don't know what it was, but I desided to avoid DI and started to use "new" operator.

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
