### ISSUE TITLE
Job is triggering once

### ISSUE THREAD

**Issue by blackhawk389** [firebase/firebase-jobdispatcher-android#131]
I implemented firebase job dispatcher to run a task every calculated minutes, but its triggering once after specified minute and after that it does not, here is how I configured

         Job job = dispatcher.newJobBuilder()
                .setService(ClsJobService.class) 
                .setTag("notification")       
                .setTrigger(Trigger.executionWindow(duration * 60, duration * 60 ))
                .setReplaceCurrent(true)
                .setLifetime(Lifetime.FOREVER)
                .setRetryStrategy(RetryStrategy.DEFAULT_EXPONENTIAL)
                .setRecurring(true)
                .build();

        dispatcher.schedule(job);   //or mustSchedule

Android version 5
Sony xperia z1s

**Comment by adil-hussain-84** [comment]
@blackhawk389: That's strange. The code looks good to me. The only difference between the code in your post above and the code I have in my app is that I'm additionally specifying `setConstraints(Constraint.ON_ANY_NETWORK)` but this shouldn't make a difference for the problem that you're seeing.

Have you tried scheduling the task on other devices? Maybe it's a problem specific to the Sony Xperia Z1S running Android version 5?

**Comment by adil-hussain-84** [comment]
One more thing to check, what are you returning in your `ClsJobService.onStartJob(JobParameters job)` method? If you're returning `true` (because you've kicked off some work to happen in a separate thread), be sure to call the `ClsJobService.jobFinished(JobParameters params, boolean needsReschedule)` method when the work in the separate thread completes.

**Comment by anandmahesh** [comment]
Same Issue faced recently in Lenovo A6000

public static Job createJob(FirebaseJobDispatcher firebaseJobDispatcher) {

        Job newJob = firebaseJobDispatcher.newJobBuilder()
                .setReplaceCurrent(false)
                .setService(JobServiceAutoStart.class)
                .setTag(JOB_AUTO_START)
                .setLifetime(Lifetime.FOREVER)
                .setRetryStrategy(RetryStrategy.DEFAULT_EXPONENTIAL)
                .setRecurring(true)
                .setTrigger(Trigger.executionWindow(60, 120))
                .build();

        return newJob;

    }

Help anyone...?

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
