### ISSUE TITLE
Failed to resolve: com.firebase:firebase-jobdispatcher:0.7.0

### ISSUE THREAD

**Issue by Patilvivek28** [firebase/firebase-jobdispatcher-android#132]
I tired using multiple versions of this repo, but every time it says like Failed to resolve.

I am using Android Studio v2.3.3 & my app details are like below :

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.example.android.APP_NAME"
        minSdkVersion 10
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

Please help me in getting this resolved ASAP.

**Comment by montwell** [comment]
I'm having the same issue.  

I resolved it by going here.
https://bintray.com/firebase/firebase-jobdispatcher/jobdispatcher#files/com%2Ffirebase%2Ffirebase-jobdispatcher%2F0.8.0

Then importing the AAR as a new module.

**Comment by ciarand** [comment]
Are you enabling the JCenter repo in your build file? Something like this: https://github.com/firebase/firebase-jobdispatcher-android/blob/b7dae549451d28401211c7eb21cbfb408513c1f1/build.gradle#L5

**Comment by montwell** [comment]
repositories {
        jcenter()
        maven { url "http://jcenter.bintray.com"}
    }

**Comment by montwell** [comment]
My issue is most likely caused by being behind a corporate firewall.

**Comment by montwell** [comment]
I fixed my issue by importing our corporate proxy cert into the java certificate authority.

Similar to this resolution.
https://stackoverflow.com/questions/21076179/pkix-path-building-failed-and-unable-to-find-valid-certification-path-to-requ

**Comment by Patilvivek28** [comment]
My issue is most likely caused by being behind a corporate firewall.

**Comment by NipunaCooray** [comment]
Fixed after restarting Android studio
