### ISSUE TITLE
Recurring unreliable 

### ISSUE THREAD

**Issue by almisoft** [firebase/firebase-jobdispatcher-android#133]
Google forces me to stop using the AlarmManager because of "Excessive Wakeups"...
I should now use JobScheduler, but my app should support older devices with API <21.
So I have to use the Firebase JobDispatcher :-(

However, in my opinion, the JobDispatcher is unreliable.
If I set the interval to every 60 secs:

13:42:28 Job created
13:42:31 onStartJob() is called 
13:43:37 onStartJob() is called 
Then gaps of 1, 10, 6, 1, 16, 12, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 12, 4, 0, 1, 8 mins.

My smartphone (Samsung Galaxy Alpha, Android 5.0.1) is connected to power an not in standby, power safe option is activated.

On Emulator (Android 7.1) first no problems:
11:48:23 Job created
11:49:23 onStartJob() is called 
11:50:23 onStartJob() is called 
11:51:23 onStartJob() is called 
11:52:23 onStartJob() is called 
...
but later gaps of several mins, too.

What am I doing wrong?

```
FirebaseJobDispatcher dispatcher = new FirebaseJobDispatcher(new GooglePlayDriver(context));
Job jobWifi = dispatcher.newJobBuilder()
.setService(ConnectionJobService.class)
.setTag("tag")
.setRecurring(true)
.setLifetime(Lifetime.FOREVER)
.setTrigger(Trigger.executionWindow(60, 60))
.setReplaceCurrent(true)
.setRetryStrategy(RetryStrategy.DEFAULT_EXPONENTIAL)
.setExtras(extras)
.build();
```

**Comment by hynra** [comment]
Any update for this ?

**Comment by unEgor** [comment]
Jobs are not allowed to run during doze mode.
Recurring jobs are going to have 15 minute period enforced by Android.

**Comment by almisoft** [comment]
> Recurring jobs are going to have 15 minute period enforced by Android.
I do not understand. Why is it possible to set a shorter period?
And - sorry about that - this is no answer to my question.

**Comment by unEgor** [comment]
Shorter period is possible because the minimum period might change over time.
The period will automatically be adjusted based if it is less than minimum.

You are not doing anything wrong.

**Comment by almisoft** [comment]
Unfortunately, I still don't understand it.
Let's make it concrete. In my example (see above) the 1-minute-period first works, later not. Why?
My devices and the emulator was not in doze mode.
Because the period is less than 15 mins? 
If I choose 15 mins or 20 mins, it will work?
Why is an 1-minute-period possible with AlarmManager but not with JobDispatcher?

**Comment by unEgor** [comment]
-Why is an 1-minute-period possible with AlarmManager but not with JobDispatcher?
Because started from android N JobScheduler uses 15 minutes minimum interval.
https://android.googlesource.com/platform/frameworks/base/+blame/1b6519b/core/java/android/app/job/JobInfo.java#79

-Let's make it concrete. In my example (see above) the 1-minute-period first works, later not. Why?
There could be multiple factors for that. FJD does not guaranty exact execution time. Jobs could be batched in order to save power.

You could use "adb shell dumpsys activity service GcmService" to understand why your job did not run.
