### ISSUE TITLE
Job Scheduler is Inconsistent in lenovo(5.0.2)

### ISSUE THREAD

**Issue by kundanlohani** [firebase/firebase-jobdispatcher-android#134]
Job service did not get call always periodically after every 30 second. It is very inconsistent some time it is getting called some time not. Below is the code. This work well in other device.
Job myJob = dispatcher.newJobBuilder()
                // the JobService that will be called
                .setService(LocationJob.class)
                        // uniquely identifies the job
                .setTag("location")
                        // one-off job
                .setRecurring(true)
                        // don't persist past a device reboot
                .setLifetime(Lifetime.FOREVER)
                        // start between 0 and 60 seconds from now
                .setTrigger(Trigger.executionWindow(1, 30))
                        // don't overwrite an existing job with the same tag
                .setReplaceCurrent(true)
                        // retry with exponential backoff
                .setRetryStrategy(RetryStrategy.DEFAULT_EXPONENTIAL)
                        // constraints that need to be satisfied for the job to run
                //.setExtras(jobBundle)
                .build();

        dispatcher.mustSchedule(myJob);

**Comment by ismaeltoe** [comment]
In fact, it is inconsistent in general. I have 2 phones (same model, same Android version, same app). Jobs are running fine in one while in another it can take hours to run. 

We can't rely 100% on it and Google continue to recommend it. That's inconceivable!

**Comment by BoondoggleLabs** [comment]
`.setTrigger(Trigger.executionWindow(1, 30))`

means: start this task between 1 and 30 seconds after the last run of this task. You might be after:

`.setTrigger(Trigger.executionWindow(30, 30))`

**Comment by unEgor** [comment]
Recurring jobs soon will have 15 minutes period enforced by the Android platform in order to save battery.
If you need to execute you job more frequently you need to schedule not recurring job at the end to your job.
Perfect timing is not guarantied.
