### ISSUE TITLE
Changed the service, will the change occur?

### ISSUE THREAD

**Issue by Amosss** [firebase/firebase-jobdispatcher-android#137]
My JobDispatcher in MainActivity onCreate looks like this:

        Job myJob = dispatcher.newJobBuilder()
                .setService(ServiceChecker.class)
                .setTag("blah")
                .setRecurring(true)
                .setLifetime(Lifetime.FOREVER)
                .setTrigger(Trigger.executionWindow(604800, 604860)) //once a week
                **.setReplaceCurrent(false)**
                .setRetryStrategy(RetryStrategy.DEFAULT_LINEAR)
                .setConstraints(Constraint.ON_ANY_NETWORK)
                .build();

Now I changed serviceChecker code. Will it be the "new" code the next time it runs (after new installation) even though setReplaceCurrent is false?
Thanks

**Comment by Amosss** [comment]
Any kind of help will be appreciated, thanks :)

**Comment by unEgor** [comment]
Hi Amosss,
FJD does not store your classes. So current version of your service will be run.
If the service was removed in new version the job won't run and will timed out currently.
In new releases the phantom jobs will canceled automatically.

**Comment by Amosss** [comment]
Thank you very much, so I understand that the setReplaceCurrent only reference the JD itself and its scheduling, correct?

**Comment by unEgor** [comment]
Correct.
replaceCurrent flag is used for timing calculation.
If the job has big period and you will send scheduling requests frequently FJD will reschedule the job all the time and reset timer. So the job might not be executed if replaceCurrent flag was set to true.

**Comment by Amosss** [comment]
Thanks!
