### ISSUE TITLE
Lifecycle aware JobService

### ISSUE THREAD

**Issue by AkshayChordiya** [firebase/firebase-jobdispatcher-android#143]
I'm using `JobService` where I want to use my `ViewModel` from the Android Architecture Components library. That means the `JobService` needs to be `LifecycleOwner`. 

I hoping to have an `LifecycleJobService` or how can one write their own?

**Comment by unEgor** [comment]
FJD is for background jobs.
It won't provide Lifecycle.

**Comment by AkshayChordiya** [comment]
I understand the reason for not providing `Lifecycle` in FJD. Then how should I get my `ViewModel` in FJD?
There is [https://stackoverflow.com/questions/44708202/observe-livedata-from-foreground-service](url) answer for using `ViewModel` in `Service` . 
Hence I thought maybe is some way for FJD

**Comment by jbxbergdev** [comment]
@unEgor, not providing a lifecycle only because it's a background Service doesn't quite make sense to me. Can you please elaborate the reasoning? Thanks.

**Comment by AkshayChordiya** [comment]
The reason why I needed was to get `ViewModel` in background service which has dependency on lifecycle. But later I realized it's not required as we can inject `Repository` instead.
