### ISSUE TITLE
Force start a job via CLI

### ISSUE THREAD

**Issue by vibinr** [firebase/firebase-jobdispatcher-android#145]
It's possible to force start a `android.app.job.JobService` via CLI, like:

`adb shell cmd jobscheduler run -f com.foo.bar.application 1`

Do we have something similar for jobdispatcher jobs? If not, how else can we test them?

**Comment by vibinr** [comment]
I came across the following command but it didn't work.
```shell
	adb shell am broadcast -a "com.google.android.gms.gcm.ACTION_TRIGGER_TASK" \
	    -e component com.foo.BarJobService \
	    -e tag BAR_JOB_TAG
```

**Comment by unEgor** [comment]
There is no such API.
You can test that the job is scheduled and what the job does using android test.
https://developer.android.com/studio/test/index.html
