### ISSUE TITLE
Job with ContentUriTrigger runs not on every URI change.

### ISSUE THREAD

**Issue by dskrashchuk** [firebase/firebase-jobdispatcher-android#146]
Actually I could not derive the pattern when it runs.

ContentProvider:
```
public Uri insert(@NonNull Uri uri, @Nullable ContentValues contentValues) {
        long rowId = getRepository(uri).insert(contentValues);

        if (rowId > 0) {
            Uri newUri = ContentUris.withAppendedId(LOCATIONS_CONTENT_URI, rowId);
            getContext().getContentResolver().notifyChange(newUri, null, true);
            return newUri;
        }
        throw new IllegalStateException("Failed to add a record into " + uri);
    }

```
Job is scheduled once in foreground service:
```
syncJobDispatcher = new FirebaseJobDispatcher(new GooglePlayDriver(this));
            JobTrigger.ContentUriTrigger trigger = Trigger.contentUriTrigger(Arrays.asList(
                    new ObservedUri(GeolocationContentProvider.LOCATIONS_CONTENT_URI, FLAG_NOTIFY_FOR_DESCENDANTS)
            ));
syncJobDispatcher.mustSchedule(syncJobDispatcher.newJobBuilder()
                    .setService(SyncJobService.class)
                    .setTag("sync-job-tag")
                    .setRecurring(true)
                  //  .setLifetime(Lifetime.FOREVER)
                    .setReplaceCurrent(false)
                    .setTrigger(trigger)
                    .setConstraints(Constraint.ON_ANY_NETWORK)
                    .setExtras(bundle)
                    .build());
```

**Comment by unEgor** [comment]
More information needed.
Please provide logs and "adb shell dumpsys activity service GcmService"

**Comment by dskrashchuk** [comment]
Please, find below:

[GcmService.txt](https://github.com/firebase/firebase-jobdispatcher-android/files/1268264/GcmService.txt)

[log.txt](https://github.com/firebase/firebase-jobdispatcher-android/files/1268267/log.txt)

**Comment by unEgor** [comment]
It looks like your job was running at the time when logs were taken. 

   (scheduled) com.example.my.app/com.firebase.jobdispatcher.GooglePlayReceiver{u=0 tag="sync-job-tag" trigger=uris{1|<content://content-provider-authority.geolocation/LocationsRepository>} requirements=[NET_CONNECTED] attributes=[] scheduled=-293s last_run=N/A jid=N/A status=**READY_ALREADY_RUNNING** retries=0}
    Not yet run.

08-31 22:11:53.256 1560-1946/system_process I/ActivityManager: Start proc 10993:com.example.my.app/u0a52 for service com.example.my.app/com.firebase.jobdispatcher.GooglePlayReceiver

**Comment by unEgor** [comment]
Please explain what is unexpected.

**Comment by dskrashchuk** [comment]
I'd expect 'onStartJob' to be called each time URI is changed...
Anyway, I've figured it out... I had to finish the job in order to fire a new one.
