### ISSUE TITLE
Couldn't view created Job in the list of testapp !

### ISSUE THREAD

**Issue by shadygoneinsane** [firebase/firebase-jobdispatcher-android#150]
Are only started jobs visible in the list ?
as I can see in the logs it says - 
`W/View: couldn't find view with id xxxxxxxxx`

And jobs get displayed in the list only after onStartJob is called !!

![capture](https://user-images.githubusercontent.com/13831192/30098830-376ed6f6-9301-11e7-87ff-c3997645c8d2.JPG)

**Comment by unEgor** [comment]
It is correct. Only started job are displayed in the test application.

**Comment by shadygoneinsane** [comment]
Would It be cool to display the pending jobs on the screen too !

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
