### ISSUE TITLE
Implement JobWorkItem features like JobScheduler.enqueue() and JobParameters.dequeueWork

### ISSUE THREAD

**Issue by ofavre** [firebase/firebase-jobdispatcher-android#151]
Android API 26 introduced [JobWorkItem](https://developer.android.com/reference/android/app/job/JobWorkItem.html)s and the ability to add work to an existing job.
This enables parallel processing of multiple items and to longer cling on a scheduled execution of your job.

It would be great if this library exposed such a feature as well.

**Comment by unEgor** [comment]
Currently we are not planning to support JobWorkItem.

FJD supports concurrent job execution.

**Comment by ravibpatel** [comment]
concurrent job execution

**Comment by ravibpatel** [comment]
I notice FJD runs job concurrently when there are multiple jobs schedule. Any way to queue it so the new job run after the previous one finishes?

**Comment by ravibpatel** [comment]
Found out that SimpleJobService synchronizes if you are running on background thread. Problem solved. Thanks for great library.
