### ISSUE TITLE
Extras 

### ISSUE THREAD

**Issue by lisemon** [firebase/firebase-jobdispatcher-android#153]
So I have an `ArrayList<String>` that I add to the bundle.

```
ArrayList<String> list = new ArrayList<String() { ... }
Bundle bundle = new Bundle();
bundle.putStringArrayList("data", list);
...
Job job = _dispatcher.newJobBuilder()
                .setService(serviceClass)
                .setExtras(bundle)
                .build();
```

But the job dispatcher only accepts Integer, Long, Double, String and Boolean:

```
FATAL EXCEPTION: main
  Process: myproject, PID: 3748
  java.lang.RuntimeException: Unable to create application myproject: com.firebase.jobdispatcher.ValidationEnforcer$ValidationException: JobParameters is invalid: Received value of type 'class java.util.ArrayList' for key 'enabled_sensors', but only the following extra parameter types are supported: Integer, Long, Double, String, and Boolean.

```
Maybe you should mention it in the documentation, or do you have an alternative solution to this? 😄 

Thanks

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
