### ISSUE TITLE
IllegalStateException: This message is already in use.

### ISSUE THREAD

**Issue by VisheshVadhera** [firebase/firebase-jobdispatcher-android#156]
Getting the following crash from one of the production apps:

`Caused by java.lang.IllegalStateException: { when=-2ms what=115 obj=ServiceArgsData{token=android.os.BinderProxy@2c8e84ca startId=2 args=Intent { act=com.google.android.gms.gcm.ACTION_TASK_READY com.firebase.jobdispatcher.GooglePlayReceiver (has extras) }} target=android.app.ActivityThread$H obj=ServiceArgsData{token=android.os.BinderProxy@2c8e84ca startId=2 args=Intent { act=com.google.android.gms.gcm.ACTION_TASK_READY cmp=com.firebase.GooglePlayReceiver.jobdispatcher (has extras) }} } This message is already in use.`

Version of firebase-job-dispatcher that we are using: `0.7.0`

Happening on the following device: Oppo A1601 (Android 5.1)

**Comment by unEgor** [comment]
Could you please provide stack trace?
It looks like the message was not created by FJD because it has "what=115".
Do you know how to reproduce it?

I think the crash is caused by a modification in the OS.
