### ISSUE TITLE
Jobs with same tag behavior

### ISSUE THREAD

**Issue by antonkazakov** [firebase/firebase-jobdispatcher-android#159]
I have problem with my jobs being stacked. According to [JobService docs](https://developer.android.com/reference/android/app/job/JobInfo.Builder.html#JobInfo.Builder(int,%20android.content.ComponentName))  JobId is unique identifier and scheduling job with same Id will just restart timer if job not executing or restart job if it's executing now. But there is no such thing as jobId here. Does job tag have same behaviour as JobId?    
```
.setTag("my-unique-tag")
.setReplaceCurrent(false)
```

Will rescheduling job with this params just create another job which will run with previous one?
Thanks.

**Comment by BenjaminEarley** [comment]
@antonkazakov, was there something that is equivalent to the JobId?
