### ISSUE TITLE
Feature request : Add a "getAllPendingJobs()" method

### ISSUE THREAD

**Issue by LouisCAD** [firebase/firebase-jobdispatcher-android#160]
Hi,
Android's JobScheduler supports getting the list of scheduled jobs via [this method](https://developer.android.com/reference/android/app/job/JobScheduler.html#getAllPendingJobs()). Could you add a similar method to Firebase Job Dispatcher please? I'm interested to discuss the API design and how it'd work under the hood

**Comment by ncaferra** [comment]
+1, this feature would be awesome

**Comment by toddshansen** [comment]
nice suggestion. Unfortunately we won't be able to add this. Please see the readme for context.
