### ISSUE TITLE
Recurring task only gets executed once or twice.

### ISSUE THREAD

**Issue by marcojansen** [firebase/firebase-jobdispatcher-android#163]
Hi,

I've followed the getting started guide and I'm trying to get a job scheduled every 5 seconds just to see if it's working. When I press the button the log shows up 1-2 times and then stops. Sometimes I get another log a few minutes later, sometimes not. The scheduler seems really random in my project. Is this what it is supposed to do?

My goal is to use this in another project where I want to send results to a server every hour when a network connection is available, but it also behaved like this in that project. I'm using Android Studio and have a Oneplus 5 and a Moto G for testing. (Same result both phones)

My manifest:
```
    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <service
            android:exported="false"
            android:name=".MySampleTask">
            <intent-filter>
                <action android:name="com.firebase.jobdispatcher.ACTION_EXECUTE"/>
            </intent-filter>
        </service>

    </application>
```

My task:
```
public class MySampleTask extends JobService {

    @Override
    public boolean onStartJob(JobParameters job) {
        Log.e("Started job!", "Should be recurring");
        return false;
    }

    @Override
    public boolean onStopJob(JobParameters job) {
        return false;
    }
}
```

My MainActivity
```
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        onlyButton = (Button) findViewById(R.id.only_button);

        onlyButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                FirebaseJobDispatcher dispatcher = new FirebaseJobDispatcher(new GooglePlayDriver(getApplicationContext()));
                Job myJob = dispatcher.newJobBuilder()
                        .setService(MySampleTask.class)
                        .setTag("my-tag0")
                        .setRecurring(true)
                        .setLifetime(Lifetime.UNTIL_NEXT_BOOT)
                        .setTrigger(Trigger.executionWindow(0,5))
                        .setReplaceCurrent(true)
                        .setRetryStrategy(RetryStrategy.DEFAULT_EXPONENTIAL)
                        .build();
                dispatcher.schedule(myJob);

            }
        });
    }
```

gradle dependencies:
```dependencies {

    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:26.+'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.firebase:firebase-jobdispatcher:0.8.2'

    testCompile 'junit:junit:4.12'
}
```

**Comment by unEgor** [comment]
Please check output of "adb shell dumpsys activity service GcmService" to verify that your job is still scheduled.
I would use Lifetime.FOREVER because the job will be lost if Google Play Services crashes.

**Comment by marcojansen** [comment]
After doing some reading and testing I think I figured out what happens. The Android system is causing it to only get executed like once 10-15min. After setting it to 15 minutes interval it works the way I expect it to.

**Comment by ZeeRooo** [comment]
@marcojansen So, there's nothing to do or you could fix the issue?

**Comment by marcojansen** [comment]
@ZeeRooo I haven't found a solution to put it lower. For the app I am working on the minimum interval of 10-15min is fine. Having it lower than that was only for testing purposes and still behaves the same way.

**Comment by hivian** [comment]
Just update your firebase to the latest version (0.8.5) It solved the problem for me.

`implementation 'com.firebase:firebase-jobdispatcher:0.8.5'`

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
