### ISSUE TITLE
Runtime exception on some devices.

### ISSUE THREAD

**Issue by antonkazakov** [firebase/firebase-jobdispatcher-android#164]
Fatal Exception: java.lang.RuntimeException
Unable to create application ru.alfabank.mobile.android.AMApp: com.firebase.jobdispatcher.ValidationEnforcer$ValidationException: JobParameters is invalid: Couldn't find a registered service with the name ru.alfabank.mobile.android.presentation.service.DataUpdateJobService. Is it declared in the manifest with the right intent-filter?

Sometimes this error occurs on random users. Especially on Samsung with android 7

**Comment by unEgor** [comment]
Hi Anton,

I think it safe to log an error instead of throwing the exception because queryIntentServices might incorrectly return an empty list. 
Feel free to create a pull request.
Otherwise it will be updated in the next release.
