### ISSUE TITLE
Provide JavaDoc or other structured documentation on the classes

### ISSUE THREAD

**Issue by hermanvandermaas** [firebase/firebase-jobdispatcher-android#165]
A great library like this one deserves a JavaDoc (auto generated with each build like on https://github.com/jitpack/jitpack.io#features) or other structured documentation. I could not find this. There is the nice class SimpleJobService but it seems not te be documented anywhere.

**Comment by toddshansen** [comment]
nice suggestion, however see the updated readme. We won't be adding this for now.
