### ISSUE TITLE
OnStopJob() not being called when device stopped being plugged with a Constraint.DEVICE_CHARGING constraint

### ISSUE THREAD

**Issue by GauthierChan** [firebase/firebase-jobdispatcher-android#166]
I have a JobService that should run only when the device is charging (it should run each time the device is being charged). When I plug my device, the Job gets started after a little while. But when I unplug it while the work is going on the job still continues with onStopJob() never being called.

I tried unplugging it while a long task task was operating (30mn+), when I plugged it again the job was finished.

Here is how I set up the Job

```java
Job backgroundJob = dispatcher.newJobBuilder()
    .setService(ComplexBackgroundJobService.class)
    .setTag(ComplexBackgroundJobService.COMPLEX_BACKGROUND_JOB_TAG)
    .setLifetime(Lifetime.FOREVER)
    .setReplaceCurrent(true)
    .setRetryStrategy(RetryStrategy.DEFAULT_LINEAR)
    .setConstraints(
            Constraint.DEVICE_CHARGING
    )
    .build();
```
With a JobService that starts a ThreadPool : 

```java
public class ComplexBackgroundJobService extends JobService {

    public static final String COMPLEX_BACKGROUND_JOB_TAG = "COMPLEX_BACKGROUND_JOB";


    @Override
    public boolean onStartJob(final JobParameters job) {

        Logger.e("Complex background job started");

        // Start the ThreadPool
        ExecutorCommandMenu.with(this)
                .setName(COMPLEX_BACKGROUND_JOB_TAG)
                .setSubmitStrategy(ExecutorConstants.SUBMIT_STRATEGY_ADD_IF_NEW_OR_REPLACE)
                .addDataProvider(new ExampleExecutorProvider(this, 200, ExecutorConstants.PRIORITY_BACKGROUND_NORMAL))
                .setCommandCompletedListener(new ExecutorContract.ExecutorCommandListener() {
                    @Override
                    public void onCommandCompleted() {

                        Logger.e("Complex background job finished with job being "+(job == null? "null": "not null"));
                        jobFinished(job, false);
                    }

                    @Override
                    public void onCommandCanceled() {

                        Logger.e("Complex background job cancelled with job being "+(job == null? "null": "not null"));
                        jobFinished(job, true);
                    }
                })
                .submit();

        return true; // Answers the question: "Is there still work going on?"
    }

    @Override
    public boolean onStopJob(JobParameters job) {

        Logger.e("Complex background job stopped");

        ExecutorCommandMenu.with(this).cancelCommand(COMPLEX_BACKGROUND_JOB_TAG);
        return true; // Answers the question: "Should this job be retried?"
    }
}
```

Happens with a Nexus 6P on 8.0.0 and using the 1.2.0.RC4 version

**Comment by DigitalKoi** [comment]
@GauthierChan Did you solve the problem?

**Comment by HimanshuNarang** [comment]
I have same issue. Any solution?

**Comment by benevolent13** [comment]
Did you get the solution?

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
