### ISSUE TITLE
Job gets triggered only on opening the App on Custom ROMs

### ISSUE THREAD

**Issue by vetkolisanket** [firebase/firebase-jobdispatcher-android#169]
I have a task to perform which requires internet and has to be performed everyday indefinitely, below is the code I had written to perform the same

```
FirebaseJobDispatcher dispatcher = new FirebaseJobDispatcher(new GooglePlayDriver(this));
        Job myJob = dispatcher.newJobBuilder()
                .setService(FirebaseJobDispatcherService.class) // the JobService that will be called 
                .setTag(Constants.ALERT_TAG)        // uniquely identifies the job 
                .setRecurring(true) 
                .setLifetime(Lifetime.FOREVER) 
                .setReplaceCurrent(true) 
                .setRetryStrategy(RetryStrategy.DEFAULT_LINEAR) 
                .setTrigger(Trigger.executionWindow(0, (int) TimeUnit.DAYS.toSeconds(1)))
                .setConstraints(Constraint.ON_ANY_NETWORK) 
                .build(); 
 
        dispatcher.mustSchedule(myJob);
```
Now the issue is, it works properly on normal devices like Moto, Samsung etc but on Custom ROMs like OnePlus, Xiaomi the job triggers only when the app is opened. Has anyone faced this issue or know how to make it work properly on Custom ROMs as well?

**Comment by unEgor** [comment]
I think background services are not allowed on those devices.
You can contact the manufactures.
I don't think that FJD can work around it.

**Comment by abhimanyuraj** [comment]
On devices with MIUI you can ask user to add your app in the autostart list of the phone using this:

`private void addAppToAutoStartList(){
        AlertDialog.Builder alertDialogBuilder = new AlertDialog.Builder(this);
        alertDialogBuilder.setTitle("Warning!");
        alertDialogBuilder.setMessage("Please add this app to the Auto Start list of your device for better performance.");
        alertDialogBuilder.setPositiveButton("Add", new DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialogInterface, int i) {
                dialogInterface.dismiss();
                try {
                    AppPreferences.getInstance(HomeActivity.this).setMiSpecialSetting(true);
                    Intent intent = new Intent();
                    intent.setComponent(new ComponentName("com.miui.securitycenter", "com.miui.permcenter.autostart.AutoStartManagementActivity"));
                    startActivity(intent);
                }catch (Exception e){
                    Toast.makeText(HomeActivity.this, "Unable to add!", Toast.LENGTH_SHORT).show();
                }
            }
        });
        alertDialogBuilder.setNegativeButton("Ignore", new DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialog, int arg1) {
                dialog.dismiss();
            }
        });
        AlertDialog alertDialog = alertDialogBuilder.create();
        alertDialog.show();
    }`

And call this method by checking for manufacturer like

` if(android.os.Build.MANUFACTURER.equalsIgnoreCase("xiaomi")) {
           addAppToAutoStartList();
        }` 

**Conclusion:** If user adds your app to autostart list then you will be able to run your job even after one key clean but there is a limitation, your job will run but not according to your time and flex, it will get called anytime after 1 day and next call might come after 2 days so there is no guarantee of periodic call. But this is the only way I can see as of now for MIUI like custom OS. And I have tested this in many Xiaomi devices having android 5 to 7 and every where the results are same.

**Comment by vetkolisanket** [comment]
Thanks for your solution, will try it out
