### ISSUE TITLE
dispatcher.schedule(myJob) Success, but never a start job （onStartJob）

### ISSUE THREAD

**Issue by ZorOuyang** [firebase/firebase-jobdispatcher-android#170]
FirebaseJobDispatcher dispatcher = new FirebaseJobDispatcher(new GooglePlayDriver(context));
        Job myJob = dispatcher.newJobBuilder()
                // the JobService that will be called
                .setService(TDPushFJDJobService.class)
                // uniquely identifies the job
                .setTag(JOB_ID_FD)
                // one-off job
                .setRecurring(false)
                // don't persist past a device reboot
                //.setLifetime(Lifetime.FOREVER)
                // start between 0 and 10 seconds from now
                .setTrigger(Trigger.executionWindow(0, 10))
                // don't overwrite an existing job with the same tag
                .setReplaceCurrent(true)
                // retry with exponential backoff
                .setRetryStrategy(RetryStrategy.DEFAULT_EXPONENTIAL)
                // constraints that need to be satisfied for the job to run
                .setConstraints(
                        Constraint.ON_ANY_NETWORK
                )
                .build();
        if (dispatcher.schedule(myJob) == SCHEDULE_RESULT_SUCCESS) {
            TDLog.i(LOG_TAG, "job scheduler success");
        } else {
            TDLog.e(LOG_TAG, "job scheduler failure");
            //TODO job schedule failure
            //schedule(context);
        }
---------------
*After that, there was never a start job task*

**Comment by unEgor** [comment]
Please checkout https://github.com/firebase/firebase-jobdispatcher-android/issues/171
