### ISSUE TITLE
Job Service is not starting by using FirebaseDispatcher eventhough getting scheduling job success

### ISSUE THREAD

**Issue by Kethu-Yerramma** [firebase/firebase-jobdispatcher-android#171]
FirebaseJobDispatcher firebaseJobDispatcher = new FirebaseJobDispatcher(new GooglePlayDriver(SampleActivity.this));
        Job myJob = firebaseJobDispatcher.newJobBuilder().setService(MyFirebaseJobService.class) // the JobService that will be called
                .setTag(JOB_ID)        // uniquely identifies the job
                // one-off job
                .setRecurring(true)
                // don't persist past a device reboot
                .setLifetime(Lifetime.UNTIL_NEXT_BOOT)
                // start between 0 and 1 seconds from now
                .setTrigger(Trigger.executionWindow(0, 1))
                // don't overwrite an existing job with the same tag
                .setReplaceCurrent(false)
                // retry with exponential backoff
                .setRetryStrategy(RetryStrategy.DEFAULT_EXPONENTIAL)
                // constraints that need to be satisfied for the job to run
                .setConstraints(
                        // only run on an unmetered network
                        Constraint.ON_UNMETERED_NETWORK,
                        // only run when the device is charging
                        Constraint.DEVICE_CHARGING
                )
                .build();

        firebaseJobDispatcher.mustSchedule(myJob);
        Log.e(TAG,"Id "+(firebaseJobDispatcher.schedule(myJob) == SCHEDULE_RESULT_SUCCESS?"Success":"Fail"));

Here is the source code.
 Log.e(TAG,"Id "+(firebaseJobDispatcher.schedule(myJob) == SCHEDULE_RESULT_SUCCESS?"Success":"Fail"));
 this gives success but service is not started.
Present I am using Nougat Version Android device.
Libraries:
 compile 'com.firebase:firebase-jobdispatcher:0.8.2'
    compile 'com.google.code.gson:gson:2.8.2'
    compile 'com.google.android.gms:play-services:11.0.4'

Please help me to how to fix it.I am facing this issue from more than 2 weeks.

**Comment by unEgor** [comment]
Please provide "adb shell dumpsys activity service GcmService" output to make sure that your job is scheduled. (You might want to delete "DeviceID: XXXXXXX" from the output)
What version on Google Play Service is running on the device?
Your job has Constraint.DEVICE_CHARGING and Constraint.ON_UNMETERED_NETWORK constraints.
Please make sure that the device is connected to WiFi network which has internet connection and is charging.

I would use Trigger.NOW instead of Trigger.executionWindow(0, 1)
For test purposes I would schedule a job without constrains.

You can use the test app to check that FJD works.
https://github.com/firebase/firebase-jobdispatcher-android/tree/master/testapp

**Comment by Kethu-Yerramma** [comment]
HI UnEgor,


Thank you so much for quick response.

Google Play Services 11.0.4. I have tested the app with single constraint but it's also not working.Trigger.NOW tried but no result.Wifi turned on. I am not able to fix this issue.I'll check your testapp.

Regards,
Kethu.
________________________________

**Comment by Rajeshr34** [comment]
Same Here. But after restarting Physical Device it started Working.

What was the problem in the device before restart???

**Comment by leofirespotter** [comment]
I think I am having the same issue. This is my start code:

> val dispatcher = FirebaseJobDispatcher(GooglePlayDriver(context))
            val job = dispatcher
                    .newJobBuilder()
                    .setService(JsLogService::class.java)
                    .setTag(TAG + System.currentTimeMillis().toString())
                    .setExtras(extras)
                    .build()
            dispatcher.mustSchedule(job)

This works on most of the devices. However on this Samsung Galaxy J7 this is what the adb shell dumpsys activity service GcmService output is, well the relevant bits:

> (scheduled) <package_name>/com.firebase.jobdispatcher.GooglePlayReceiver{u=0 tag="JsLogService1516829801725" trigger=window{start=0s,end=1s,earliest=-14s,latest=-13s} requirements=[NET_ANY] attributes=[] scheduled=-14s last_run=N/A jid=N/A status=READY_BATTERY_LOW retries=0 client_lib=FIREBASE_JOB_DISPATCHER-1}
    Not yet run.

the battery is at 77% and charging.

The list of pending scheduled services is like 100+ long

**Comment by NitroG42** [comment]
It happens on our devices (Samsung) when the eco mode is enabled and background network is restricted. I wonder if there is a way to detect this mode to warn the user...

**Comment by Rajeshr34** [comment]
i switched to evernote its works perfectly for me.
https://github.com/evernote/android-job

**Comment by NitroG42** [comment]
I just found a way to get through, using this: https://stackoverflow.com/a/32627788/702229

**Comment by hugebelieve** [comment]
This issue is still not resolved...

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
