### ISSUE TITLE
Multiple services scheduling

### ISSUE THREAD

**Issue by DmitryVolynski** [firebase/firebase-jobdispatcher-android#173]
Hi guys, I've got two independent services and try to schedule both of them like this:

        TrackingService.startService(this, userUuid, 0, 15);
        SettingsService.startService(this, userUuid, 0, 15);

startService methods are static and look like this:

        Bundle bundle = new Bundle();
        bundle.putString(StringKeys.CURRENT_USER_UUID_KEY, userUuid);

        FirebaseJobDispatcher dispatcher =
                new FirebaseJobDispatcher(new GooglePlayDriver(context));

        Job trackingJob = dispatcher.newJobBuilder()
                .setTag(SettingsService.TAG)
                .setService(SettingsService.class)
                .setRecurring(true)
                .setExtras(bundle)
                .setLifetime(Lifetime.FOREVER)
                .setReplaceCurrent(true)
                .setTrigger(Trigger.executionWindow(windowStart, windowEnd))
                .setRetryStrategy(RetryStrategy.DEFAULT_EXPONENTIAL)
                .build();

        dispatcher.schedule(trackingJob);

When app started only first service is actually scheduled and running (i logged onStartJob, onStopJob etc). If I comment first line, the second service is scheduled and work normally. What am I doing wrong?

p.s. when I use only one service, everything works fine.

**Comment by unEgor** [comment]
Hi Dmitry,

Second job overwrites first because you use the same TAG and Service.

**Comment by DmitryVolynski** [comment]
unEgor, thanks for fast reply. TrackingService.startService looks different:

        Bundle bundle = new Bundle();
        bundle.putString(StringKeys.CURRENT_USER_UUID_KEY, userUuid);

        Job trackingJob = dispatcher.newJobBuilder()
                .setTag(TrackingService.TAG)
                .setService(TrackingService.class)
                .setExtras(bundle)
                .setRecurring(true)
                .setLifetime(Lifetime.FOREVER)
                .setReplaceCurrent(true)
                .setTrigger(Trigger.executionWindow(windowStart, windowEnd))
                .setRetryStrategy(RetryStrategy.DEFAULT_EXPONENTIAL)
                .build();

        dispatcher.schedule(trackingJob);

I tried to consider that

**Comment by unEgor** [comment]
Check output of "adb shell dumpsys activity service GcmService"
To verify that your jobs are scheduled.

**Comment by toddshansen** [comment]
no additional update since oct 2017 so marking closed
