### ISSUE TITLE
Not allowed to run service in background - Android 8

### ISSUE THREAD

**Issue by linuxjet** [firebase/firebase-jobdispatcher-android#175]
I just started getting this issue randomly.  

`public static void schedule(Context context, int time) {

    FirebaseJobDispatcher dispatcher = new FirebaseJobDispatcher(new GooglePlayDriver(context));
    Job myJob = dispatcher.newJobBuilder()
        .setService(StatisticsService.class) // the JobService that will be called
        .setTag(TAG)        // uniquely identifies the job
        .setRecurring(true)
        .setReplaceCurrent(true)
        .setTrigger(Trigger.executionWindow(time * 60,(time * 60) + 10))
        .setLifetime(Lifetime.FOREVER)
        .setRetryStrategy(RetryStrategy.DEFAULT_LINEAR)
        .setConstraints(Constraint.ON_ANY_NETWORK)
        .build();
    dispatcher.mustSchedule(myJob);
  }`

10-25 23:00:47.715 E/AndroidRuntime(16414): FATAL EXCEPTION: main
10-25 23:00:47.715 E/AndroidRuntime(16414): Process: com.linuxjet.apps.agave, PID: 16414
10-25 23:00:47.715 E/AndroidRuntime(16414): java.lang.RuntimeException: Unable to start receiver com.linuxjet.apps.agave.receivers.StatisticsReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.linuxjet.apps.agave/.services.StatisticsService }: app is in background uid UidRecord{bf2e857 u0a129 RCVR idle procs:1 seq(0,0,0)}
10-25 23:00:47.715 E/AndroidRuntime(16414):   at android.app.ActivityThread.handleReceiver(ActivityThread.java:3259)
10-25 23:00:47.715 E/AndroidRuntime(16414):   at android.app.ActivityThread.-wrap17(Unknown Source:0)
10-25 23:00:47.715 E/AndroidRuntime(16414):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
10-25 23:00:47.715 E/AndroidRuntime(16414):   at android.os.Handler.dispatchMessage(Handler.java:105)
10-25 23:00:47.715 E/AndroidRuntime(16414):   at android.os.Looper.loop(Looper.java:164)
10-25 23:00:47.715 E/AndroidRuntime(16414):   at android.app.ActivityThread.main(ActivityThread.java:6541)
10-25 23:00:47.715 E/AndroidRuntime(16414):   at java.lang.reflect.Method.invoke(Native Method)
10-25 23:00:47.715 E/AndroidRuntime(16414):   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
10-25 23:00:47.715 E/AndroidRuntime(16414):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
10-25 23:00:47.715 E/AndroidRuntime(16414): Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.linuxjet.apps.agave/.services.StatisticsService }: app is in background uid UidRecord{bf2e857 u0a129 RCVR idle procs:1 seq(0,0,0)}
10-25 23:00:47.715 E/AndroidRuntime(16414):   at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1505)
10-25 23:00:47.715 E/AndroidRuntime(16414):   at android.app.ContextImpl.startService(ContextImpl.java:1461)
10-25 23:00:47.715 E/AndroidRuntime(16414):   at android.content.ContextWrapper.startService(ContextWrapper.java:644)
10-25 23:00:47.715 E/AndroidRuntime(16414):   at android.content.ContextWrapper.startService(ContextWrapper.java:644)
10-25 23:00:47.715 E/AndroidRuntime(16414):   at com.linuxjet.apps.agave.receivers.StatisticsReceiver.onReceive(SourceFile:25)
10-25 23:00:47.715 E/AndroidRuntime(16414):   at android.app.ActivityThread.handleReceiver(ActivityThread.java:3252)
10-25 23:00:47.715 E/AndroidRuntime(16414):   ... 8 more

**Comment by mandeep-singh-ck** [comment]
Why was this closed? Was there a fix?

**Comment by unEgor** [comment]
The app targeted Android O but was not ready for it.
https://developer.android.com/about/versions/oreo/background.html

**Comment by linuxjet** [comment]
Can this issue be resolved?  I know I closed it, but it was a mistake.  The issue persists and I don't see a way to set FirebaseJobDispatcher to run startForegroundService()

**Comment by ogeidix** [comment]
FirebaseJobDispatcher is already compatible with Android O (be sure to be using a recent version)
The issue seems to be in your code:
com.linuxjet.apps.agave.receivers.StatisticsReceiver.onReceive(SourceFile:25)

**Comment by unEgor** [comment]
Please check out https://developer.android.com/about/versions/oreo/background.html

**Comment by yoav85** [comment]
@linuxjet if you solved this issue, can you please explain what was wrong in your code?
@unEgor perhaps you could find an example of a correct usage for such scenario?
