### ISSUE TITLE
Internal keys in JobParameters#getExtras()

### ISSUE THREAD

**Issue by jberkel** [firebase/firebase-jobdispatcher-android#176]
Javadoc says:

```java
/** The optional set of user-supplied extras associated with this Job. */
```
[JobParameters.java#L58](https://github.com/firebase/firebase-jobdispatcher-android/blob/master/jobdispatcher/src/main/java/com/firebase/jobdispatcher/JobParameters.java#L58)

When I call that method from my `JobService` I see lots of unrelated keys: 

```
{com.firebase.jobdispatcher.tag=INCOMING, 
 com.firebase.jobdispatcher.trigger_type=1
``` 

etc.

These keys should probably be filtered out before the job is passed to the service, or else be documented (`BundleProtocol` is package-private).

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
