### ISSUE TITLE
can't resolve dependency

### ISSUE THREAD

**Issue by Shiwanand** [firebase/firebase-jobdispatcher-android#178]
Android studio 3.0 can't resolve dependency given in this project for jobdispatcher.

**Comment by Ahmed3Elshaer** [comment]
i used the previous version and it worked with me 
`implementation 'com.firebase:firebase-jobdispatcher:0.8.4'`

**Comment by rmazajev** [comment]
Same here, 0.8.5 not building when using gradle plugin 3.0.1. Works with 0.8.4.

**Comment by FabianTerhorst** [comment]
0.8.5 works for me.

**Comment by rmazajev** [comment]
OK, it worked then i have updated gms library
`classpath 'com.google.gms:google-services:3.1.1'`
previously I used 3.0.0. So no problem here.

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
