### ISSUE TITLE
Custom Retry Strategy

### ISSUE THREAD

**Issue by antelopsolutions** [firebase/firebase-jobdispatcher-android#179]
Hello,

I am wondering why it is not possible to set a custom retry strategy in case of job failure:

More precisely, the developer can only define the way backoff must be increased (either exponentially or linearly) but it is not possible to change initial backoff value nor maximum backoff value (they are set to 30 sec and 3600 sec respectively and they cannot be changed).

Thanks!

**Comment by michaeldiener** [comment]
It is possible, just not well documented:
https://github.com/firebase/firebase-jobdispatcher-android/issues/115

**Comment by antelopsolutions** [comment]
Thanks a lot!
