### ISSUE TITLE
Confusing nullability annotations in JobService

### ISSUE THREAD

**Issue by GavinDBrown** [firebase/firebase-jobdispatcher-android#180]
When scheduling an async job we need to return `true` from `onStartJob` and later call `jobFinished` when finished. However, `onStartJob` has no nullability annotation on it's `JobParameters` parameter, whereas `jobFinished` requires a `@NonNull JobParameters`.

 It's not clear if `onStartJob` will always have a nonnull `JobParameters` or if this is a case the caller needs to handle. Hopefully it's just a matter of adding the `@NonNull` annotation to `onStartJob` (and maybe `onStopJob`).

`public abstract boolean onStartJob(JobParameters job);`
`public final void jobFinished(@NonNull JobParameters job, boolean needsReschedule)`

**Comment by davidtcdeveloper** [comment]
Same confusion here. It would be great to have this adjusted or at least more clear.
