### ISSUE TITLE
JobService not starting when app closed in API 25 only.

### ISSUE THREAD

**Issue by KulwinderSinghRahal** [firebase/firebase-jobdispatcher-android#181]
In Nougat 7.1.2 job is not starting when app is closed but with the same code job Service started if app is opened 
I am using this code 
```
val job = jobDispatcher.newJobBuilder()
             .setLifetime(Lifetime.FOREVER)
             .setService(AutoFetchService::class.java)
             .setTag("fetchAtNight")
             .setRecurring(false)
             .setReplaceCurrent(true)
             .setTrigger(Trigger.executionWindow(60, 60))
             .setConstraints(Constraint.ON_ANY_NETWORK).build()
val result = jobDispatcher.schedule(job)

```

**Comment by dreamchaser96** [comment]
Same here
Have you managed to find an answer?

**Comment by KulwinderSinghRahal** [comment]
also posted on stackoverflow but did not get any response till

**Comment by jakal23** [comment]
I have the same problem.Also bind service also stopped without calling onDestroy method. And all Threads terminated inside of job.

**Comment by jakal23** [comment]
The problem is come from Google play service. Play service should start Job service with bind auto_create. In my case job restarted after 4 minutes after app destroyed.

**Comment by KulwinderSinghRahal** [comment]
did you got any solution ? ,

**Comment by jakal23** [comment]
No I did not. In my opinion its depend of phone state (Network, Battery, etc..). Anyway I lose my data, because service does not respond.

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
