### ISSUE TITLE
Job starts too soon on changes in content URI

### ISSUE THREAD

**Issue by kushalkadaba** [firebase/firebase-jobdispatcher-android#185]
I have a job scheduled to run if there are changes in Contacts.  I have noticed however that the job is triggered as soon as I start editing my contacts in the Google Contacts app. Is there a way to delay this? I know that the JobScheduler API has a method `setTriggerContentUpdateDelay` to avoid this exact problem. Is there something similar or any plan to add this in?

**Comment by jberkel** [comment]
Same problem here. Often this content changes come in batches, so it does make sense to wait for a bit before triggering. Obviously this could also be implemented in client code but it does make sense to have it in the library, and to keep API compatibility (it's already diverged quite a bit) with JobScheduler.

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
