### ISSUE TITLE
Job not reschedule when app is killed

### ISSUE THREAD

**Issue by adelpuva** [firebase/firebase-jobdispatcher-android#186]
This is my code:

```
final int periodicity =360 ;
Job.Builder builder = dispatcher.newJobBuilder()
  .setService(MyService.class)
  .setTag(JOB_TAG)
  .setLifetime(Lifetime.FOREVER)
  .setRecurring(true)
  .setReplaceCurrent(true)
  .setTrigger(Trigger.executionWindow(periodicity, periodicity + 60))
  .setConstraints(Constraint.ON_ANY_NETWORK)
  .setRetryStrategy(RetryStrategy.DEFAULT_LINEAR);
```
If I kill my app (from device settings) Job is never called.

The configuration is incorrect? Or is correct that jobs will not scheduled if user (or system) kill app?

I'm developing on 6.0.1, this is my Manifest:
```
...
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
...
<service
   android:name=".MyService"
   android:exported="false"
   android:permission="android.permission.BIND_JOB_SERVICE">
   <intent-filter>
     <action android:name="com.firebase.jobdispatcher.ACTION_EXECUTE" />
    </intent-filter>
</service>
```

Thank you!

**Comment by marc0x71** [comment]
Try  

`setReplaceCurrent(true)`

and execute

`dispatcher.cancelAll();`

before create new jobs
;)

**Comment by deepakrana0011** [comment]
@

**Comment by FisnikIbishi** [comment]
Could you try this?

dispatcher.cancel(JOB_TAG)
dispatcher.schedule(job)

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
