### ISSUE TITLE
Exact job every 5 minutes not working

### ISSUE THREAD

**Issue by jplazcano87** [firebase/firebase-jobdispatcher-android#187]
i need to perform a job every 5 minutes, i'm using the Execution window trigger

```
    final int periodicity = (int) MINUTES.toSeconds(5);
    Timber.tag(TAG).d("Periodicity Interval " + periodicity + " seconds");

    String jobIdentifier = String.valueOf(routeId);
    JobTrigger.ExecutionWindowTrigger jobTrigger = Trigger.executionWindow(0, periodicity);

    Job myJob = dispatcher.newJobBuilder()
        .setService(DiagnosticDataJob.class)
        .setExtras(jobDataExtra)
        .setTag(jobIdentifier)
        .setLifetime(Lifetime.UNTIL_NEXT_BOOT)
        .setReplaceCurrent(true)
        .setConstraints(Constraint.ON_ANY_NETWORK)
        .setTrigger(jobTrigger)
        .setRecurring(true)
        .build();

    dispatcher.mustSchedule(myJob);
```

but the trigger is not running at exact 5 minutes interval, this is my logcat output

```
11-14 09:28:44.778 17009-17009/ D/DiagnosticDataJob: Starting Job
11-14 09:37:18.583 17009-17009/ D/DiagnosticDataJob: Starting Job
11-14 09:37:21.840 17009-17009/ D/DiagnosticDataJob: Starting Job
11-14 09:42:08.856 17009-17009/ D/DiagnosticDataJob: Starting Job
11-14 09:57:44.790 17009-17009/ D/DiagnosticDataJob: Starting Job
11-14 09:57:45.953 17009-17009/ D/DiagnosticDataJob: Starting Job
11-14 10:02:31.101 17009-17009/ D/DiagnosticDataJob: Starting Job
11-14 10:10:01.191 17009-17009/ D/DiagnosticDataJob: Starting Job
11-14 10:10:01.346 17009-17009/ D/DiagnosticDataJob: Starting Job
11-14 10:18:16.306 17009-17009/ D/DiagnosticDataJob: Starting Job
11-14 10:18:16.506 17009-17009/ D/DiagnosticDataJob: Starting Job
11-14 10:22:46.608 17009-17009/ D/DiagnosticDataJob: Starting Job
11-14 10:40:02.751 17009-17009/ D/DiagnosticDataJob: Starting Job
11-14 10:42:47.670 17009-17009/ D/DiagnosticDataJob: Starting Job
11-14 10:48:21.958 17009-17009/2 D/DiagnosticDataJob: Starting Job
11-14 10:48:22.262 17009-17009/ D/DiagnosticDataJob: Starting Job
11-14 10:53:38.235 17009-17009/D/DiagnosticDataJob: Starting Job
11-14 10:59:38.434 17009-17009/ D/DiagnosticDataJob: Starting Job
```

am i missing something like priority or other parameter?

**Comment by amansri29** [comment]
JobTrigger.ExecutionWindowTrigger jobTrigger = Trigger.executionWindow(0, periodicity);

Change to JobTrigger.ExecutionWindowTrigger jobTrigger = Trigger.executionWindow(periodicity - 10, periodicity);

this is the windows in between service will execute.

**Comment by alisolutions** [comment]
I am also getting the same issue, Please provide the appropriate solution. It should start the job within the execution window. why it's taking more time?
Strange thing is few days ago I was set the execution window [10, 11] (in seconds), and that was working quite fine. I mean job become start within 10 to 13 seconds. But now it is being started after 30 seconds. Thats very inconsistent.
My use case is, I want to run a job periodically after every 10 seconds, is the right framework which I am using to schedule the periodic jobs?

**Comment by laviua** [comment]
alisolutions, +1

**Comment by alisolutions** [comment]
@laviua 
I found the following solutions, if you want to run a job exactly after certain time like within 5 seconds.

- Go with [evernote/android-job](https://github.com/evernote/android-job) and schedule a non-periodic job and then recursively reschedule a new job within the executed service. Also set the execution window without any tolerance, like if you want to run a job after each 5 seconds then set the execution window [5, 5]. 

- Simply go with [AlarmManager](https://developer.android.com/reference/android/app/AlarmManager.html) API. That will work accurately, but of course that will consume more battery.

The issue I found with FireJobDispatcher is, its using JobSchedule and Android has clearly documented that minimum window for the periodic job is 15mins.

Let me know if you need any other info.

- M. Ali

**Comment by laviua** [comment]
@alisolutions 
I decided to use HandlerThread with Handler(looper)
it can schedule Runnable with a short time period. in my case it can be 500ms or 5sec

Thanks for your solution

**Comment by jplazcano87** [comment]
i'm sticking with the AlarmManager api in order to execute an exact job, nevertheless is important to be aware of battery consumption. @laviua i'm curious about your use case, why you need to run a job in some short period of time? maybe if you are performing a polling to a web service, the solution is using push notifications.

**Comment by laviua** [comment]
use case is polling sensors activity

**Comment by lotussinha** [comment]
On android 7.1 i cant able to execute job using evernote . Since the app has been swiped off from recent the background job stops and no service running in android 7.1.1.Please let me know any one solved this issue

**Comment by jplazcano87** [comment]
the way to go now is using the work manager library from android architecture components, there's no point to keep this thread

**Comment by bbincybbaby** [comment]
but work manager support only minimum duration of 15 minute
