### ISSUE TITLE
JobService Not starting on Boot Complete Lenovo k5

### ISSUE THREAD

**Issue by sanidhya09** [firebase/firebase-jobdispatcher-android#195]
Job locationUploadJob = firebaseJobDispatcher.newJobBuilder()
                    .setService(LocationFollowJobService.class)
                    .setTag(mTag)
                    .setRecurring(false)
                    .setLifetime(Lifetime.FOREVER)
                    .setTrigger(Trigger.executionWindow(seconds, seconds + 45))
                    .setReplaceCurrent(true)
                    .setRetryStrategy(RetryStrategy.DEFAULT_LINEAR)
                    .setConstraints(Constraint.ON_ANY_NETWORK)
                    .build();

            firebaseJobDispatcher.schedule(locationUploadJob);

**Comment by abhimanyuraj** [comment]
Add RECEIVE_BOOT_COMPLETED to your manifest file
`<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>`

**Comment by rahulsamaddar** [comment]
Device: OnePlus 5T
I have added the permission 
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
Manifest Entry:- 
<receiver
            android:name=".BootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>

MyBootReceiver class
public class BootReceiver extends BroadcastReceiver {


    @Override
    public void onReceive(Context context, Intent intent) {
        Log.d("boot_boot","Received BOOT COMPLETED");
        if (UserUtil.isUserRegistered(context)) {
            ChatService.startService(context);
            MetaDataUpdaterBroadcast.scheduleAlarmManager_ForUpdatingMetadata(context);
        }
    }
}
Still No luck:
Logcat data:-
01-23 16:29:43.811 3466-5236/? E/NetworkScheduler.TED: Couldn't start service: Intent { act=com.google.android.gms.gcm.ACTION_TASK_READY cmp=net.one97.paytm/com.firebase.jobdispatcher.GooglePlayReceiver (has extras) }
01-23 16:29:43.812 3466-5312/? E/NetworkScheduler: Unknown result code received: 4

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
