### ISSUE TITLE
job is not started when passing either serializable or parcelable data 

### ISSUE THREAD

**Issue by tsironis13** [firebase/firebase-jobdispatcher-android#197]
Bundle bundle = new Bundle();
        bundle.putString("auth_token", authToken);
        bundle.putString("fcm_token", fcmToken);
        bundle.putSerializable("user_device", userDevice);
        scheduleJob(mFirebaseJobDispatcher.newJobBuilder()
                                            .setService(SyncFcmTokenJob.class)
                                            .setTag("sync_fcm_job")
                                            .setTrigger(Trigger.executionWindow(0, 0))
                                            .setConstraints(Constraint.ON_ANY_NETWORK)
                                            .setRetryStrategy(RetryStrategy.DEFAULT_EXPONENTIAL)
                                            .setExtras(bundle)
                                            .build());

job is only triggered when 'bundle.putSerializable("user_device", userDevice)' is commented out.

**Comment by morphine9** [comment]
What device are you testing on ? 
For devices less than API 21, it maybe working. 
Between 21 and 25 may not 
and then again start working for API 26 and above (depending on the complexity of the bundle)

Had the same issue. Use bundle adhering to [PersistableBundle](https://developer.android.com/reference/android/os/PersistableBundle.html)(for devices between API 21 and API 25), there is [setTransientExtras()](https://developer.android.com/reference/android/app/job/JobInfo.Builder.html#setTransientExtras(android.os.Bundle)) that can handle Bundles for API 26 and above.

**Comment by tsironis13** [comment]
i am testing on Android Nougat API 25. Unfortunately there is no such method available in the library. setTransientExtras() exists in the base JobInfo.Builder of the JobScheduler framework.

**Comment by morphine9** [comment]
Faced the same problem - userDevice should be of simple type (only primitives and List and Maps)

I circumvented the issue with transforming complex objects to json via GSON, jackson etc. and using  bundle.setString(USER_DEVICE, USER_DEVICE_JSON_STRING)
which also persists across device reboots

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
