### ISSUE TITLE
Creating a one off JobService does not work.

### ISSUE THREAD

**Issue by Zeroe31890** [firebase/firebase-jobdispatcher-android#198]
```
                final FirebaseJobDispatcher jobDispatcher = new FirebaseJobDispatcher(new GooglePlayDriver(this));
                final Job leJob = jobDispatcher.newJobBuilder()
                        .setService(MyAwesomeService.class)
                        .setTag(MyAwesomeService.JOB_SERVICE_ID)
                        .setReplaceCurrent(false)
                        .setRecurring(false)
                        .setTrigger(Trigger.executionWindow(0, 0))
                        .build();
                jobDispatcher.mustSchedule(leJob);
```

Using the code examples I imagine the above code should work to create a single job and execute it a few minutes later. But this does not work. I tested it when `setRecurring` was true and it works fine. So the code within it doesn't seem like the problem. Am I missing something when scheduling a one-off job?

Device: 6P 8.0
Firebase-jobdispatcher:0.8.1

**Comment by hivian** [comment]
I think your proprem is the execution Window. Try:

`.setTrigger(Trigger.NOW)`

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
