### ISSUE TITLE
E/NetworkScheduler.ATC: Unable to resolve correct action against com.firebase.jobdispatcher.GooglePlayReceiver for user #0 to instantiate callback. Not executing task

### ISSUE THREAD

**Issue by MVLangkilde** [firebase/firebase-jobdispatcher-android#199]
I am currently trying to replace my IntentService classes with JobService classes of the Firebase Jobdispatcher library. However, I've ran into some issues.

I followed the docvumentation, but "onStartJob(JobParameters job)" is never called. 
I found something interesting in my log:

> com.google.android.gms.persistent E/NetworkScheduler.ATC: Unable to resolve correct action against com.firebase.jobdispatcher.GooglePlayReceiver for user #0 to instantiate callback. Not executing task.

It sounds like there are some problems with the dependencies, which is why I added the following exclude. Unfortunately, that didn't solve it.
```
    compile 'com.google.android.gms:play-services-gcm:11.4.2'
    compile ("com.firebase:firebase-jobdispatcher-with-gcm-dep:0.8.5") {
        exclude module: "play-services-gcm"
    }
```

I don't really know what to do from here. Is this a known issue? (can't seem to find anything similar).
Any help will be greatly appreciated.

**Comment by PingForward** [comment]
The same thing. I'm trying to start it on emulator API 26 with google api support

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
