### ISSUE TITLE
Job is not rescheduled with targetSdkVersion 26

### ISSUE THREAD

**Issue by carlocodega** [firebase/firebase-jobdispatcher-android#200]
I'm trying to change the targetSdkVersion to 26 (Android 8) but I realized that jobs are never recheduled, and subsequent triggers for the same job don't work.

Device: Google Pixel

I'm scheduling using a content provider trigger:

Job job = dispatcher.newJobBuilder()
                    .setService(AutoImportJob.class)
                    .setTag(buildJobTag(observedUri))
                    .setRecurring(true)
                    .setLifetime(Lifetime.UNTIL_NEXT_BOOT)
                    .setTrigger(Trigger.contentUriTrigger(Arrays.asList(observedUri)))
                    .setReplaceCurrent(true)
                    .setRetryStrategy(RetryStrategy.DEFAULT_LINEAR)
                    .setExtras(extras)
                    .build();

Note: jobs rescheduling works properly by reverting targetSdkVersion to 25

**Comment by carlocodega** [comment]
Can I enable JobDispatcher logs? Can they help?

**Comment by YaasinAJDI** [comment]
make sure you add <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
