### ISSUE TITLE
Network constraints ignored

### ISSUE THREAD

**Issue by sandeep-voxer** [firebase/firebase-jobdispatcher-android#201]
Here's some test code I wrote to schedule a job - it's a modification of the Job Scheduler sample, modified to use Firebase job dispatcher instead.

I found that the network constraints are completely ignored - i.e when I require WiFi (unmetered), the job is run even though the device WiFi was switched off and only cellular data was active.

When I specify network type any as a constraint, and then turn on airplane mode so that there's no internet connection, the job is run anyway. I want the job to only run if there's a network connection. How do I do that? If there's no network connection immediately, then I want the job to be run as soon as internet connection is available (whether LTE or WiFi).

```
jobTag = RandomStringUtils.randomAlphabetic(15);
        final Job.Builder builder = jobDispatcher.newJobBuilder()
            .setService(MyJobService.class)
            .setTag(jobTag)
            .setRecurring(false)
            .setReplaceCurrent(false);

        int[] constraints = new int[]{};
        int delay = 0;
        int deadline = 0;

        String delayString = mDelayEditText.getText().toString();
        if (!TextUtils.isEmpty(delayString)) {
            delay = Integer.parseInt(delayString) * 1000;
        }

        String deadlineString = mDeadlineEditText.getText().toString();
        if (!TextUtils.isEmpty(deadlineString)) {
            deadline = Integer.parseInt(deadlineString) * 1000;
        }
        
        builder.setTrigger(Trigger.NOW);
        
        boolean requiresUnmetered = mWiFiConnectivityRadioButton.isChecked();
        constraints = ArrayUtils.add(constraints, Constraint.ON_ANY_NETWORK);
        if (requiresUnmetered) {
            constraints = ArrayUtils.add(constraints, Constraint.ON_UNMETERED_NETWORK);
        }
        if(mRequiresIdleCheckbox.isChecked()) constraints = ArrayUtils.add(constraints, Constraint.DEVICE_IDLE);
        if(mRequiresChargingCheckBox.isChecked()) constraints = ArrayUtils.add(constraints, Constraint.DEVICE_CHARGING);
        
        builder.setConstraints(constraints)
               .setLifetime(Lifetime.FOREVER)
               .setRetryStrategy(RetryStrategy.DEFAULT_LINEAR);

        // Extras, work duration.
        Bundle extras = new Bundle();
        String workDuration = mDurationTimeEditText.getText().toString();
        if (TextUtils.isEmpty(workDuration)) {
            workDuration = "1";
        }
        extras.putLong(WORK_DURATION_KEY, Long.valueOf(workDuration) * 1000);
        builder.setExtras(extras);

        // Schedule job
        Log.i(TAG, "Scheduling job");
        jobDispatcher.mustSchedule(builder.build());
```

**Comment by vit001** [comment]
Same issue here. Network constraints are ignored.

**Comment by 3mph4515** [comment]
Also faced with similar trouble: have ImmediateTrigger and ANY_NETWORK constraint but job run even without the Internet connection.

**Comment by garnesen** [comment]
Just started using this tool today and ran into the same issue. From my minimal testing, it seems that setting the trigger to be something besides immediate fixes it (for example, I set mine to run within a minute).

**Comment by cbriseno** [comment]
Same issue here, Constraint.ON_UNMETERED_NETWORK is being ignored in my jobs.

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
