### ISSUE TITLE
Perform a job only when network is disconnected

### ISSUE THREAD

**Issue by itsdebs** [firebase/firebase-jobdispatcher-android#202]
I am using Paho as a client for Mqtt which uses background service. My requirement is that I start the service on any network and stop it when the network is disconnected. Is there any way to do this using Job scheduler? [Here](https://stackoverflow.com/questions/48006948/perform-a-job-using-firebase-job-dispatcher-only-when-there-is-no-network-availa) is the SO question which went unanswered.

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
