### ISSUE TITLE
dispatcher.cancel() is not working

### ISSUE THREAD

**Issue by 3llomi** [firebase/firebase-jobdispatcher-android#203]
i am trying to cancel a Job when the user clicks on a Button
my scenario is like this:
a message received from **FCM** contains a **URL**  .
inside `onMessageReceived `  the job will run and start downloading that file
```java
private void scheduleJob(final Message message) {
        FirebaseJobDispatcher dispatcher = FBJDSingleton.getInstance(this);
        Bundle myExtrasBundle = new Bundle();
        myExtrasBundle.putString("messageId", message.getMessageId());
        myExtrasBundle.putString("link", message.getContent());
        myExtrasBundle.putInt("type", message.getType());
        myExtrasBundle.putString("receiverId", message.getFromId());


        Job myJob = dispatcher.newJobBuilder()
                .setService(MyJobService.class)
                .setTag(message.getMessageId())
                .setRecurring(false)
                .setLifetime(Lifetime.UNTIL_NEXT_BOOT)
                .setTrigger(Trigger.NOW)
                .setReplaceCurrent(false)
                .setRetryStrategy(RetryStrategy.DEFAULT_EXPONENTIAL)
                .setConstraints(Constraint.ON_ANY_NETWORK)
                .setExtras(myExtrasBundle)
                .build();


        dispatcher.mustSchedule(myJob);
    }
```
```java
@Override
    public boolean onStartJob(JobParameters job) {
        Log.d("3llomi", "ON Start JOB");
        Toast.makeText(this, "ONSTART JOB", Toast.LENGTH_SHORT).show();
        String messageId = job.getExtras().getString("messageId");
        String link = job.getExtras().getString("link");
        int type = job.getExtras().getInt("type");
        String receiverId = job.getExtras().getString("receiverId");
        downloadFile(link, type, messageId, receiverId, -1);
        return false;
    }
```

when the user clicks the cancel Button it should stop the Download Job

```java
            //onClick in Activity
            FBJDSingleton.getInstance(this).cancel(messageId);
```
and here is the Singleton Class 

```java 
public class FBJDSingleton {
    private static FirebaseJobDispatcher firebaseJobDispatcher;

    private FBJDSingleton() {}

     public static FirebaseJobDispatcher getInstance(Context context) {
        if (firebaseJobDispatcher == null) {
            firebaseJobDispatcher = new FirebaseJobDispatcher(new GooglePlayDriver(context));
        }
        return firebaseJobDispatcher;
    }
}
```

**Comment by adsonafonso** [comment]
are you returning "false" onStopJob @3llomi

**Comment by 3llomi** [comment]
@adsonafonso yes i am returning **false** because i don't want to re-run the Job again

**Comment by adsonafonso** [comment]
@3llomi https://github.com/firebase/firebase-jobdispatcher-android/issues/110 this seems related.
Need to call `jobFinished(job, false)`. Let me know if this works for you

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
