### ISSUE TITLE
Firebase.jobdispatcher with RxJava2 doesn't work asynchronously

### ISSUE THREAD

**Issue by Delphian2015** [firebase/firebase-jobdispatcher-android#205]
I am trying to start Firebase jobdispatcher asynchronously using RxJava2.

```
@Override
    public boolean onStartJob(JobParameters job) {
    LOG.debug("start job");
    Completable.fromAction(new Action() {
            @Override
            public void run() throws Exception {
                LOG.debug("run");
                startMethod();
            }
        }).subscribeOn(Schedulers.io())
          .observeOn(Schedulers.mainThread())
          .subscribeWith(new DisposableCompletableObserver() {
            @Override
            public void onComplete() {
                LOG.debug("onComplete");
                onStopJob(job);
            }

            @Override
            public void onError(Throwable e) {

            }
        });
        return true;
}

@Override
    public boolean onStopJob(JobParameters job) {
        LOG.debug("stop job");
        return true;
}

 public void startMethod(){ 
       LOG.debug("startMethod");
}
```

In log I see:
main: [start job]
RxCachedThreadScheduler-1: [run]

When i added subscribeOn(Schedulers.io()) line the startMethod() doesn't start, if I delete this line the startMethod() starts in Main thread. But sometimes startMethod starts and I see in LOG. 
Even with an empty method it works unstably.

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
