### ISSUE TITLE
android.os.BadParcelableException

### ISSUE THREAD

**Issue by Aquarids** [firebase/firebase-jobdispatcher-android#208]
java.lang.RuntimeException:Unable to start activity ComponentInfo{com.ushowmedia.mipha/com.google.android.gms.auth.api.signin.internal.SignInHubActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2678)
android.os.BadParcelableException:ClassNotFoundException when unmarshalling: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
android.os.Parcel.readException(Parcel.java:1548)
android.os.Parcel.readException(Parcel.java:1499)

**Comment by ciarand** [comment]
I don't see any indication in the stack trace that this is being caused by the FJD library. We don't start activities, and we don't call into the Google Play services APIs that would do that.

Feel free to reopen if you know how the FJD library is causing this issue.
