### ISSUE TITLE
Dispatch Job Immediately

### ISSUE THREAD

**Issue by accelonome** [firebase/firebase-jobdispatcher-android#212]
I've tried with both NOW & Executionwindow(0,0). NOW creates a genuine delay & (0,0) does not trigger in my case. Trying to send a message to pusher using a dispatcher. Instant message sending is critical in my case.

**Comment by sandy-8925** [comment]
@accelonome  - I faced the same problem, I've found evernote/android-job library works better. If all of your conditions are met, your job gets executed immediately. It also supports enforcing network constraints unlike Firebase job dispatcher.

**Comment by ashishkrishnan** [comment]
@accelonome Did you face the issue on the first job? or was it the second job which was scheduled but not executed.

**Comment by lordplagus02** [comment]
I have the same issue, and I think the debugger has something to do with it (but don't quote me on that) :tongue: 
It happens on my first job, once the first job starts the rest flow smoothly, but it's _always_ late to start.

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
