### ISSUE TITLE
Add a Pull Request Template and Issue Template

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-jobdispatcher-android#215]
As discussed. this repository should have a pull request template and an issue template.

Some good examples:
https://raw.githubusercontent.com/firebase/firebase-js-sdk/master/.github/ISSUE_TEMPLATE.md
https://raw.githubusercontent.com/firebase/firebase-js-sdk/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by toddshansen** [comment]
would be nice to have but in light of updated readme closing this issue.
