### ISSUE TITLE
Explain how recurring works

### ISSUE THREAD

**Issue by lujop** [firebase/firebase-jobdispatcher-android#22]
I haven't found any information about how recurring jobs works.
When is exactly a recurring job scheduled?
If I have an executing window trigger of 10 minutes one hour in future, can I expect to be rescheduled also at a 10 minutes window one hour later than first execution finished?

**Comment by Gaket** [comment]
Are there any updates in docs?

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
