### ISSUE TITLE
service is not running   it is in doze mode

### ISSUE THREAD

**Issue by aolmez** [firebase/firebase-jobdispatcher-android#220]
i create a new job and write log when it is running. it is correctly but it does not work after a certain time
i think it is in doze mode. how can set it is run every time? Can you help me?

   FirebaseJobDispatcher dispatcher = new FirebaseJobDispatcher(new GooglePlayDriver(this));
        Job job = dispatcher.newJobBuilder()
                .setLifetime(Lifetime.FOREVER)
                .setService(TimelyService.class)
                .setTag("timely_service")
                .setRecurring(true)
                .setTrigger(Trigger.executionWindow(0, Constants.KEY_TIME_SERVICE_INTERVAL)) // 2 min
                .setRetryStrategy(RetryStrategy.DEFAULT_EXPONENTIAL)
                .build();
        dispatcher.mustSchedule(job);

**Comment by toddshansen** [comment]
it is working as intended when it doesn't run in doze and doze on the go mode. it may run during doze maintenance windows though.
