### ISSUE TITLE
Excessive Alarm Manager wakeups

### ISSUE THREAD

**Issue by krishnasajja** [firebase/firebase-jobdispatcher-android#221]
I'm using Firebase job dispatcher to get notifications whenever there is a change to user's calendar data so that I can auto-import and process the new update or events.

Here's my usage:

```
JobTrigger.ContentUriTrigger trigger = Trigger.contentUriTrigger(Arrays.asList(
                new ObservedUri(CalendarContract.Events.CONTENT_URI, FLAG_NOTIFY_FOR_DESCENDANTS)));

       mJobDispatcher.mustSchedule(mJobDispatcher.newJobBuilder()
                .setTag(BuildConfig.APPLICATION_ID + "calendar-job-tag")
                .setService(CalendarJobService.class)
                .setRecurring(true)
                // .setLifetime(Lifetime.FOREVER)
                .setReplaceCurrent(false)
                .setTrigger(trigger)
                .build());
```
In Google play developer console, In Android vitals sections, the app got flagged for bad behavior for 'Excessive Alarm Manager wakeups'. 

I'm not using Alarm Manager directly anywhere. So, my guess is that the Firebase dispatcher job is causing the trigger.

Any suggestions on if I'm configured the job correctly or what can be done to fix this? Or If I'm completely off on my guess. Thanks!

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
