### ISSUE TITLE
Android O set finished my recurring job with  Play Services 12.2.21

### ISSUE THREAD

**Issue by VincenzoWiman** [firebase/firebase-jobdispatcher-android#225]
This is my job scheduler 

 
 ```
FirebaseJobDispatcher dispatcher = new FirebaseJobDispatcher(new GooglePlayDriver(ctx));
        Job job = dispatcher.newJobBuilder()
                .setTrigger(Trigger.executionWindow(0,  15))
                .setTag("FakeJobs")
                .setService(FakeJob.class)
                .setLifetime(Lifetime.FOREVER)
                .setRecurring(true)
                .setReplaceCurrent(true)
                .build();

        dispatcher.mustSchedule(job);

 ```
With Play Services  11.7.46
 

>   (scheduled) me.wiman.test.free/com.firebase.jobdispatcher.GooglePlayReceiver{u=0 tag="FakeJobs" trigger=window{start=0s,end=15s,earliest=-8s,latest=6s} requirements=[NET_ANY] attributes=[PERSISTED,RECURRING] scheduled=-8s last_run=N/A jid=N/A status=PENDING retries=0}
>     Not yet run.

With Play Services 12.2.21

> ( finished) [me.wiman.test.free/com.firebase.jobdispatcher.GooglePlayReceiver:FakeJobs,u0]
>    successes: 1 reschedules: 0 failures: 0 timeouts: 0 invalid_service: 0 total_runtime_millis: 82

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
