### ISSUE TITLE
Job is not rescheduling

### ISSUE THREAD

**Issue by eitanaviv** [firebase/firebase-jobdispatcher-android#226]
Hi there,
I've been trying to implement a JobService that will reschedule, but with no success and with the following error:
`03-20 15:11:52.190 22796-22796/com.eitan.myapp E/ActivityThread: Service com.firebase.jobdispatcher.GooglePlayReceiver has leaked ServiceConnection com.firebase.jobdispatcher.JobServiceConnection@2cf02e4 that was originally bound here
    android.app.ServiceConnectionLeaked: Service com.firebase.jobdispatcher.GooglePlayReceiver has leaked ServiceConnection com.firebase.jobdispatcher.JobServiceConnection@2cf02e4 that was originally bound here
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1532)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1424)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1605)
        at android.app.ContextImpl.bindService(ContextImpl.java:1557)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:684)
        at com.firebase.jobdispatcher.ExecutionDelegator.executeJob(ExecutionDelegator.java:110)
        at com.firebase.jobdispatcher.GooglePlayMessageHandler.handleStartMessage(GooglePlayMessageHandler.java:98)
        at com.firebase.jobdispatcher.GooglePlayMessageHandler.handleMessage(GooglePlayMessageHandler.java:67)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

The code i'm using is this;
```java
Job myJob = getDispatcher(context).newJobBuilder()
        .setService(ActivityRecognitionJobDispatcher.class)
        .setTag(JOB_DISPATCHER_ACTIVITY_RECOGNITION_NAME)
        .setReplaceCurrent(true)
        .setRecurring(true)
        .setTrigger(Trigger.executionWindow(5, 10))
        .setLifetime(Lifetime.FOREVER)
        .setRetryStrategy(RetryStrategy.DEFAULT_LINEAR)
        .setConstraints(Constraint.ON_ANY_NETWORK)
        .build();
getDispatcher(context).mustSchedule(myJob);
```

JobService code:
```java
public class ActivityRecognitionJobDispatcher extends JobService {

    @Override
    public boolean onStartJob(final JobParameters job) {
        Toast.makeText(this, "Job started", Toast.LENGTH_SHORT).show();

        //My simple task

        return true;
    }

    @Override
    public boolean onStopJob(JobParameters job) {
        return false;
    }
}
```

Maybe i'm wrong here, but the job gets called only once and then the above error appears.
I'm using Samsung Galaxy S8+ (Android 8.0) and Android Studio Emulator (Android 8.1) with both Google Play Services version 12.2.21.
Any ideas?

**Comment by Xavron** [comment]
If this is based on "GooglePlayReceiver has leaked ServiceConnection" then that in of itself does not keep a job from being scheduled again and working additional times.

This should be close and another opened for a different reason if need be.

**Comment by Xavron** [comment]
Tis not "GooglePlayReceiver has leaked ServiceConnection" at fault kind sir.

That leak should be due to setTrigger(Trigger.executionWindow(5, 10)) in use here. 5 and 10 seconds isn't enough time. At 300, 360 (seconds or 5-6 minute window) the leak should disappear.

In any case, its possible to make a job run again even at 5, 6 seconds and have the leak every time.

**Comment by Xavron** [comment]
Tis not "GooglePlayReceiver has leaked ServiceConnection" at fault kind sir.

Though may have something to do with .setTrigger(Trigger.executionWindow(5, 10)) as 5-10 seconds isn't much time and that's pretty heavy spamming of the job cycle anyway.

Even at 5-6 minute window the leak can happen and still the job will occur again. Notice in the below example that even though its a 5-6 minute window in use, the job occurs at about 13-14 minutes later too, but it still does.

In any case, even at 5-6 seconds its possible to have onStartJob() called

05-12 10:13:01.202 11325-11325/com.x E/ActivityThread: Service com.firebase.jobdispatcher.GooglePlayReceiver has leaked ServiceConnection...
05-12 10:14:00.133 11325-11325/com.x E/-: starting service...
05-12 10:14:00.143 11325-11325/com.x E/-: (onStartCommand) Service started...
05-12 10:14:18.269 11325-14448/com.x E/-: Service finishing successfully!
05-12 10:14:18.270 11325-11325/com.x E/-: onDestroy()
05-12 10:27:54.403 11325-11325/com.x E/ActivityThread: Service com.firebase.jobdispatcher.GooglePlayReceiver has leaked ServiceConnection...
05-12 10:29:09.546 11325-11325/com.x E/-: starting service...
05-12 10:29:09.557 11325-11325/com.x E/-: (onStartCommand) Service started...

I do think this should be closed as "GooglePlayReceiver has leaked ServiceConnection" is not at fault.

This example was on a Samsung A7 with Oreo.

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
