### ISSUE TITLE
java.lang.IllegalStateException in android.app.Activity.performResume

### ISSUE THREAD

**Issue by hamzaydia** [firebase/firebase-jobdispatcher-android#228]
My app is crashing in Android 7.0+, I use The Firebase JobDispatcher v0.8.5 And this is the report:

> **java.lang.RuntimeException:**

> 1. at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3873)
> 2. at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3914)
> 3. at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3070)
> 4. at android.app.ActivityThread.-wrap14 (ActivityThread.java)
> 5. at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1659)
> 6. at android.os.Handler.dispatchMessage (Handler.java:102)
> 7. at android.os.Looper.loop (Looper.java:154)
> 8. at android.app.ActivityThread.main (ActivityThread.java:6816)
> 9. at java.lang.reflect.Method.invoke (Native Method)
> 10. at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1563)
> 11. at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1451)

> Caused by: **java.lang.IllegalStateException:**

> 1. at android.app.Activity.performResume (Activity.java:7154)
> 2. at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3850)

**Comment by tasneembohra** [comment]
I am also facing this issue, but I am still not sure it's because of dispatcher.

**Comment by hamzaydia** [comment]
@tasneembohra I think it's related to the battery saving in some devices like Huawei, Xiaomi..., They force stop the app after some time.

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
