### ISSUE TITLE
Not able to reschedule the job

### ISSUE THREAD

**Issue by varunam** [firebase/firebase-jobdispatcher-android#230]
Hi, Please find below is the flow.
1. A job has been created to show notification every 15 minutes if the app is not opened.
2. Step 1 is working perfectly. But the requirement says if user opens in middle of 15 minutes, then the job should be rescheduled and it should pop up after 15 minutes he opened the app.
3. I have setReplaceCurrent to true also. But even I open the app at 13th minute, the notification should pop up at 28th minute however it is still popping up at 15th minute.

Please suggest if I am doing anything wrong or this is an issue with the JobDispatcher.

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
