### ISSUE TITLE
Is this library actively maintained?

### ISSUE THREAD

**Issue by yaronlevi** [firebase/firebase-jobdispatcher-android#232]
We are considering several options for handling background jobs on android.
The main contenders are **Evernote's android-job** and **firebase-jobdispatcher-android**

firebase-jobdispatcher-android seems like a good choice overall but seeing quite a lot of open issues and no commits in the last months got us worried.

It would be great if one of the core maintainers could shed some light on the status of the library regarding future updates.

Any help on this issue would be much appreciated (-:

**Comment by michaeldiener** [comment]
My personal guess and hope is that there will be some news regarding this next week at Google I/O. Fingers crossed, otherwise I'll switch to another library ;)

**Comment by yaronlevi** [comment]
@michaeldiener So let's say there won't be any news regarding **firebase-jobdispatcher-android**, would you recommend **Evernote's android-job** as the second option?

One thing about Evernote's android-job that comes as a surprise is that it does not support the option of restarting jobs after a **force swipe/reboot**. It says so in the [FAQ](https://github.com/evernote/android-job/wiki/FAQ) under "What happens with jobs after the app was forced killed?":

As far as I understand firebase-jobdispatcher-android **did** support rescheduling after force swipe/reboot. Do you have any ideas how to make Evernote's library deal with this situation or any other library that can achive this result?

**Comment by michaeldiener** [comment]
After day 1 of Google I/O I think the way forward is "WorkManager" from the new Android Jetpack. AFAIK this is in a preview/alpha stage for now.

https://developer.android.com/topic/libraries/architecture/workmanager
https://codelabs.developers.google.com/codelabs/android-workmanager/#0

What I wonder is, that they mention the following: "... WorkManager might use JobScheduler, Firebase JobDispatcher, or AlarmManager." According to this, Firebase JobDispatcher could be used internally, but why isn't it updated then? Still a bit of a mystery to me, but there will be a more detailed session about WorkManager tomorrow at I/O and hopefully they will clarify:
https://events.google.com/io/schedule/?sid=74b6f068-02c9-4d6d-8ce0-0164f844a0db

**Comment by yaronlevi** [comment]
@michaeldiener Thats great news! Do you have any reference to a place it states the preview/alpha stage? How long do you think it takes until it's production ready?

**Comment by michaeldiener** [comment]
In the session today it was mentioned at the end that WorkManager has still alpha state. There should be a YouTube video of that session soon. It is also mentioned in one of the links I provided earlier:

> WorkManager is currently in alpha - when stable, it will be the recommended task scheduler on Android.


It can be used with Firebase JobScheduler as underlying framework for lower API levels or also without it. I asked the Firebase team here at Google I/O about their JobScheduler and it will be continued from what I have heard.
So seems like there has been a bit of parallel development between the Android (WorkManager) and Firebase team. IMHO probably only WorkManager will survive, but unfortunately it will take a few months until it is stable. I'll probably stick with the JobScheduler until then and hope it gets some updates soon.

**Comment by toddshansen** [comment]
see updated readme.
