### ISSUE TITLE
FirebaseJobDispatcher is getting crashed when triggered.

### ISSUE THREAD

**Issue by Josh2941** [firebase/firebase-jobdispatcher-android#233]
**Descrpition**
I am scheduling a job using `FirebaseJobDispatcher` to run after a certain amount of time. When the time of execution comes, it gets triggered but it is getting crashed and the dispatched job is not running.

**Libraries**
com.google.firebase:firebase-core:12.0.1
com.google.firebase:firebase-messaging:12.0.1

I am not able to update the firebase libraries to latest version(15.0.0) since I am using Google Auth wherein if I update it to 15.0.0, I end up with the mixed versions of google and firebase libraries error eventhough I am not mixing versions (It gets mixed internally).

Another problem on updating library is that Google's new library update doesn't allow `play-services` alias target to pull in Google Play Service components (Referred from [Release Notes](https://developers.google.com/android/guides/releases)). And they don't seem to provide an alternative way to get the libraries in the Release Notes. 

**Stacktrace**
`05-04 18:09:35.951 1641-1863/? W/ActivityManager: Scheduling restart of crashed service <package>/com.firebase.jobdispatcher.GooglePlayReceiver in 51782ms
05-04 18:09:35.951 1641-1863/? W/ActivityManager: Scheduling restart of crashed service <package>.service.GSService in 1000ms
`

**Steps to Reproduce**
1. Dispatch a job with `setTrigger()`.
2. Wait for the job to be triggered.

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
