### ISSUE TITLE
Workmanager

### ISSUE THREAD

**Issue by FabianTerhorst** [firebase/firebase-jobdispatcher-android#237]
Will https://developer.android.com/topic/libraries/architecture/workmanager replace firebase-jobdispatcher-android? It looks like it's made for the exact same use case.

**Comment by recheej** [comment]
Workmanager encapsulates many previous background apis that Android had, including job dispatcher (since job scheduler is only api 21+). So my guess is, I doubt it. But who knows.

**Comment by toddshansen** [comment]
See updated readme
