### ISSUE TITLE
Repeating job logging error even after job was cancelled, app deleted and phone restarted! How do I make it stop!!!

### ISSUE THREAD

**Issue by JonG1984** [firebase/firebase-jobdispatcher-android#238]
I schedule a repeating job, which works fine, and every now and then triggers my job.  Over a period of time I began noticing the following error being popping up in Logcat.  

`05-11 14:03:19.446 5133-7451/? E/ExecutionCriteria: Package unavailable for task: com.test.package/com.firebase.jobdispatcher.GooglePlayReceiver{u=0 tag="config-repeat-job" trigger=window{start=114s,end=120s,earliest=-13253s,latest=-13247s} requirements=[NET_UNMETERED,CHARGING] attributes=[PERSISTED,RECURRING] scheduled=-13367s last_run=N/A jid=N/A status=PENDING retries=0 client_lib=FIREBASE_JOB_DISPATCHER-1}`

This became more and more frequent.  I have tried the following:

- Cancelling the job - Log still appears to be generate
- Restarting the phone - Log still appears to be generate
- Deleting the app, and restarting the phone - Log still appears to be generate

My question is, what have I done wrong, and how do I make these logs stop! I'm using Firebase within an SDK which will be distributed to 3rd party applications, so its important I don't clog up their logs with these error messages.

This is the job that i've configured.

val dispatcher = FirebaseJobDispatcher(GooglePlayDriver(context))
val job = dispatcher.newJobBuilder()
        .setService(ConfigService::class.java)
        .setTag("config-repeat-job")
        .setRecurring(true)
        .setTrigger(Trigger.executionWindow(120, 120))
        .setReplaceCurrent(true)
        .setLifetime(Lifetime.FOREVER)
        .setRetryStrategy(RetryStrategy.DEFAULT_EXPONENTIAL)
        .setConstraints(
                Constraint.ON_UNMETERED_NETWORK,
                Constraint.DEVICE_CHARGING)
        .setExtras(extras)
        .build()
dispatcher.schedule(job)

Any advice will be very welcome.

**Comment by MohamedElidrissi** [comment]
Same problem happening to me, logs are appearing everywhere even though I uninstalled the app like 10 hours ago, they don't seem like they care

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
