### ISSUE TITLE
Add AlarmManager-based Driver for pre-L, non-Google devices

### ISSUE THREAD

**Issue by johan12345** [firebase/firebase-jobdispatcher-android#24]
If I understood it correctly, this library only includes a Driver implementation for GcmNetworkManager, which only works on devices where Google Play Services is installed. Is it planned to add another Driver implementation that works on devices without this (on both API >= 21 using JobScheduler and on API < 21 with a different implementation using AlarmManager)? Otherwise, I don't really see a big advantage of using this library over talking to GcmNetworkManager directly.

**Comment by kenyee** [comment]
ditto..should be part of the support libraries for API < 21.  Or part of the firebase libraries (core?)

**Comment by johan12345** [comment]
@kenyee Well, probably not the Firebase libraries, because those are not Open Source. On the other hand, including it in the Support Library would be problematic because then a Support Library would be (at least optionally) dependant on Google Play Services. I think it'd be fine if the library would be available  (separately) on JCenter (#1, #30) and usable without Play Services (as described above)

**Comment by ciarand** [comment]
There's definitely a plan to add a JobScheduler-backed Driver implementation for pre-L devices. We're also actively working on adding some features that were technically infeasible to add to the GcmNetworkManager library. We'll hopefully have some more details on that next week.

Like johan12345@ pointed out, it's not really currently feasible to include this in the standard support libraries because it has a dependency on Google Play services. We may revisit that question once we have some Drivers that work sans Google Play services.

**Comment by johan12345** [comment]
@ciarand Is there also a plan to create a (AlarmManager-based) Driver implementation that works on pre-L devices without Play Services, like the one in https://github.com/evernote/android-job ? Some apps may not want to depend on Google Play Services for various reasons (e.g. wanting to keep the app completely Open Source or to be compatible with non-Play devices).

**Comment by ciarand** [comment]
Yes, L+ is what I meant. There are plans for an AlarmManager implementation, but the JobScheduler version is a higher priority for us.

I'm going to rename this issue to focus on the AlarmManager implementation and use #32 for the JobScheduler.

**Comment by kendersec** [comment]
Any ETA on this?

**Comment by amolrajoba** [comment]
Any update on firebase support for pre-L with an AlarmManager implementation ?

**Comment by misrakli** [comment]
Any progress here?

**Comment by unEgor** [comment]
Sorry, no progress so far.

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
