### ISSUE TITLE
Clarify constraint ON_ANY_NETWORK

### ISSUE THREAD

**Issue by Seikilos** [firebase/firebase-jobdispatcher-android#247]
In my opinion the constraint comment for this is unclear and I would request an update. I would contribute to the project but I am unsure of what this constraint actually mean:
```
  /**
   * Only run the job when a network connection is available. If both this and {@link
   * #ON_UNMETERED_NETWORK} is provided, {@link #ON_UNMETERED_NETWORK} will take precedence.
   */
  public static final int ON_ANY_NETWORK = 1 << 1;
```

From the _point of view of the application / service_ triggered by this: Will the constraint be fulfilled when the device has the ability to connect to a network in terms of an enabled mobile data or wifi? Or will it be fulfilled whenever something else has enabled radio communication bringing the device to the radio's high power state?
I assume the first one but from the application's perspective the second one could also make sense in terms of conserving battery life.

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
