### ISSUE TITLE
Unclear: Possible to derive from JobTrigger to create custom one?

### ISSUE THREAD

**Issue by Seikilos** [firebase/firebase-jobdispatcher-android#248]
To improve the domain in which I can use this product I was trying to inherit from JobTrigger to create a custom one allowing to trigger on other conditions than `Now`, `ExecutionWindow` and `ContentUri`. While deriving and assigning was no problem, there seems to be literally no interface I can implement.
Is it not possible to derive from JobTrigger to create custom ones? If so I would request this as a feature.

AFAIK work-arounding on this forces me to use nested job dispatching, where the wrapper job performs my custom trigger check and the dispatching the original one which I initially wanted to guard with my custom trigger.

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
