### ISSUE TITLE
Provide support for a pure Java module

### ISSUE THREAD

**Issue by ZakTaccardi** [firebase/firebase-jobdispatcher-android#25]
Please abstract this library so it can work in the context of a pure java environment. 

Business logic often can (and should be) simplified in a pure java module. The concept of jobs certainly fits this criteria.

This can be done with with having a pure java "core" jobdispatcher module, and a second "android" implementation of it. Somewhat similar to how Retrofit adds RxJava support without bundling it into the core library.

**Comment by ciarand** [comment]
This is an interesting idea, but for now we'd like to focus on making this the best possible job library on Android. That means taking advantage of the tools and components available in the Android framework and Google Play services.
