### ISSUE TITLE
Clarify setReplaceCurrent

### ISSUE THREAD

**Issue by Seikilos** [firebase/firebase-jobdispatcher-android#250]
This is again a request for documentation.
The method `setReplaceCurrent` has only this as its comment and code:

`` /** Sets whether this Job should replace pre-existing Jobs with the same tag. */``

It is unclear what happens if a job is currently executing, will the job be stopped and its `onStopJob` being called? Will the new job be discarded because one with the same job is currently running? Will it be queued and executed?

**Comment by ChampIsMe** [comment]
Am still waiting for the answer to this question too

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
