### ISSUE TITLE
Job not being called

### ISSUE THREAD

**Issue by kishoreannapureddy** [firebase/firebase-jobdispatcher-android#252]
My recurring job does not get called after few runs. When I run
`adb shell dumpsys activity service GcmService`, I get the following:

> (scheduled) com.domain.app/com.firebase.jobdispatcher.GooglePlayReceiver{u=0 tag="myjob" trigger=window{start=0s,end=900s,earliest=-4046s,latest=-3146s} requirements=[NET_CONNECTED] attributes=[PERSISTED,RECURRING] scheduled=-4046s last_run=N/A jid=N/A status=READY_APP_STOPPED retries=0 client_lib=FIREBASE_JOB_DISPATCHER-1}

You can see from the 'earliest' and 'latest', that the job is delayed a lot. I have seen cases when the delay is much more. Also, I specifically see that when status changes to 'READY_APP_STOPPED' the job stops to run. Job typically runs when the status is 'PENDING' and stops to run after it changes to 'READY_APP_STOPPED'. This change happens after few runs. Is there a way I can make the job run properly?

**Comment by djjames** [comment]
tys

**Comment by alexhorsa** [comment]
It may be that the minimum repeat interval has to be 15 MINUTES

See here https://stackoverflow.com/a/48269482/9400836

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
