### ISSUE TITLE
executing service com.firebase.jobdispatcher.GooglePlayReceiver

### ISSUE THREAD

**Issue by ZebpayDipen** [firebase/firebase-jobdispatcher-android#256]
com.firebase.jobdispatcher.GooglePlayReceiver

"main" tid=1 Runnable
"main" prio=5 tid=1 Runnable
| group="main" sCount=0 dsCount=0 obj=0x737a0960 self=0xb8822c78
| sysTid=17779 nice=0 cgrp=default sched=0/0 handle=0xb6f4ab34
| state=R schedstat=( 0 0 0 ) utm=19868 stm=387 core=0 HZ=100
| stack=0xbe28e000-0xbe290000 stackSize=8MB
| held mutexes= "mutator lock"(shared held)
at com.google.android.gms.internal.firebase_database.zziv.getValue (zziv.java)
at com.google.android.gms.internal.firebase_database.zzif.getValue (zzif.java)
at com.google.android.gms.internal.firebase_database.zzif.getValue (zzif.java)
at com.google.android.gms.internal.firebase_database.zzif.getValue (zzif.java)
at com.google.firebase.database.DataSnapshot.getValue (DataSnapshot.java)
at zebpay.Application.deepstream.FirebaseStreamConnection$1$1.onRateChanged (FirebaseStreamConnection.java:123)
at zebpay.Application.home.HomeRateChangeListener.onDataChange (HomeRateChangeListener.java:35)
at com.google.android.gms.internal.firebase_database.zzfc.zza (zzfc.java)
at com.google.android.gms.internal.firebase_database.zzgx.zzdr (zzgx.java)
at com.google.android.gms.internal.firebase_database.zzhd.run (zzhd.java)
at android.os.Handler.handleCallback (Handler.java:739)
at android.os.Handler.dispatchMessage (Handler.java:95)
at android.os.Looper.loop (Looper.java:168)
at android.app.ActivityThread.main (ActivityThread.java:5845)
at java.lang.reflect.Method.invoke! (Native method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:797)
at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:687)

#########################################################

"ReferenceQueueDaemon" tid=3 Waiting
"ReferenceQueueDaemon" daemon prio=5 tid=3 Waiting
| group="system" sCount=1 dsCount=0 obj=0x32c07100 self=0xb97c3388
| sysTid=17785 nice=0 cgrp=default sched=0/0 handle=0xb435b930
| state=S schedstat=( 0 0 0 ) utm=15 stm=25 core=3 HZ=100
| stack=0xb4259000-0xb425b000 stackSize=1038KB
| held mutexes=
at java.lang.Object.wait! (Native method)

waiting on <0x042d5e35> (a java.lang.Class<java.lang.ref.ReferenceQueue>)
at java.lang.Daemons$ReferenceQueueDaemon.run (Daemons.java:155)
locked <0x042d5e35> (a java.lang.Class<java.lang.ref.ReferenceQueue>)
at java.lang.Thread.run (Thread.java:818)
Step 2: Describe your environment
Android device: almost all the device
Android OS version: all
Google Play Services version: 15.0.2
Firebase/Play Services SDK version:com.firebase:firebase-jobdispatcher:0.8.5
Step 3: Describe the problem:
We used firebase job dispatcher to update the rate in widget an we are fetching rate from firebase only.
We received too many ANRs for this.
Any kind of help is needful.

**Comment by ZebpayDipen** [comment]
Hey @samtstern  Any update for this...the ANR rates are getting high day by day

**Comment by CaptMustache** [comment]
Same here. It was about a week ago when ANR rates started to get higher

**Comment by wangxvbin** [comment]
Executing service com.energysh.drawshow/com.firebase.jobdispatcher.GooglePlayReceiver

I have encountered the same problem and hope that Google engineers can help, thank you!

**Comment by Ranjan101** [comment]
I am Also getting same error
11-28 17:17:18.382 935-958/? E/ActivityManager: ANR in com.softagekyc.circuit
    PID: 16243
    Reason: Executing service com.softagekyc.circuit/com.firebase.jobdispatcher.GooglePlayReceiver
    Load: 4.17 / 4.12 / 4.18
    CPU usage from 0ms to 5148ms later:
      54% 935/system_server: 19% user + 34% kernel / faults: 7918 minor 87 major
      10% 1523/com.android.phone: 5% user + 5.6% kernel / faults: 3999 minor 10 major
      7.9% 1175/com.android.systemui: 4.2% user + 3.6% kernel / faults: 2388 minor 2 major
      0% 326/debuggerd64: 0% user + 0% kernel / faults: 3319 minor 17 major
      0.1% 1540/com.quicinc.cne.CNEService: 0.1% user + 0% kernel / faults: 2422 minor 2 major
      0% 1559/android.process.media: 0% user + 0% kernel / faults: 2060 minor
      0% 1449/com.qualcomm.qcrilmsgtunnel: 0% user + 0% kernel / faults: 2058 minor
      0% 1466/com.android.server.telecom: 0% user + 0% kernel / faults: 2531 minor
      0% 1484/com.asus.audiowizard: 0% user + 0% kernel / faults: 2230 minor
      0% 1504/dk.icepower.icesound: 0% user + 0% kernel / faults: 2230 minor 2 major
      0.9% 276/surfaceflinger: 0.3% user + 0.5% kernel / faults: 28 minor 1 major
      0.5% 183/mmcqd/0: 0% user + 0.5% kernel
      0% 156/cfinteractive: 0% user + 0% kernel
      0% 3/ksoftirqd/0: 0% user + 0% kernel
      0% 12/ksoftirqd/1: 0% user + 0% kernel
      0% 29/kworker/0:1H: 0% user + 0% kernel
      0% 34/kworker/u9:0: 0% user + 0% kernel
      0% 96/kswapd0: 0% user + 0% kernel
      0.1% 688/adbd: 0% user + 0.1% kernel
      0.1% 1137/VosRXThread: 0% user + 0.1% kernel
      0% 1247/wpa_supplicant: 0% user + 0% kernel
      0% 1897/com.google.android.gms.persistent: 0% user + 0% kernel / faults: 1 minor
      0% 15052/kworker/u8:4: 0% user + 0% kernel
      0.1% 17124/logcat: 0% user + 0.1% kernel
      0% 17245/kworker/0:0: 0% user + 0% kernel
    26% TOTAL: 11% user + 14% kernel + 1.2% iowait + 0% softirq
    CPU usage from 4605ms to 5124ms later:
      5.7% 935/system_server: 0% user + 5.7% kernel / faults: 2 minor
        3.8% 958/ActivityManager: 0% user + 3.8% kernel
      2.4% 276/surfaceflinger: 0% user + 2.4% kernel
        1.2% 408/Binder_1: 1.2% user + 0% kernel
        1.2% 410/DispSync: 1.2% user + 0% kernel
    6.1% TOTAL: 2.3% user + 2.8% kernel + 0.9% iowait

**Comment by MichelleMcCabe** [comment]
Getting them quite regularly...

2019-01-22 14:30:53.075 3980-3995/? E/ActivityManager: ANR in com.myownpackage
    PID: 14304
    Reason: executing service com.myownpackage/com.firebase.jobdispatcher.GooglePlayReceiver
    Load: 9.4 / 9.41 / 7.96
    CPU usage from 0ms to 18272ms later (2019-01-22 14:30:34.768 to 2019-01-22 14:30:53.039):
      10% 3980/system_server: 5.6% user + 4.8% kernel / faults: 3189 minor 196 major
      2.3% 14371/kworker/u16:0: 0% user + 2.3% kernel
      2.1% 14194/kworker/0:1: 0% user + 2.1% kernel
      0.1% 893/kswapd0: 0% user + 0.1% kernel
      1.2% 7333/com.android.bluetooth: 0.7% user + 0.5% kernel / faults: 1392 minor 77 major
      1.2% 4627/com.android.phone: 0.7% user + 0.4% kernel / faults: 1404 minor 123 major
      0.6% 7610/com.android.vending: 0.4% user + 0.2% kernel / faults: 992 minor 72 major
      1.1% 858/cfinteractive: 0% user + 1.1% kernel
      1% 1534/mmc-cmdqd/0: 0% user + 1% kernel
      1% 4616/com.sec.imsservice: 0.6% user + 0.4% kernel / faults: 1780 minor 459 major
      0.8% 54/kworker/u16:2: 0% user + 0.8% kernel
      0.8% 4378/com.android.systemui: 0.5% user + 0.3% kernel / faults: 1124 minor 77 major
      0.8% 4640/com.sec.epdg: 0.5% user + 0.3% kernel / faults: 1674 minor 240 major
      0.8% 14372/kworker/u16:1: 0% user + 0.8% kernel
      0.7% 4518/adbd: 0.1% user + 0.6% kernel / faults: 270 minor
      0.6% 1879/decon0-vsync: 0% user + 0.6% kernel
      0.6% 7/rcu_preempt: 0% user + 0.6% kernel
      0.6% 3335/logd: 0.2% user + 0.3% kernel / faults: 11 minor
      0% 4610/com.sec.sve: 0% user + 0% kernel / faults: 2866 minor 319 major
      0% 3600/media.codec: 0% user + 0% kernel / faults: 992 minor 50 major
      0.4% 4357/com.sec.android.inputmethod: 0.3% user + 0.1% kernel / faults: 822 minor 14 major
      0% 4589/com.sec.vsimservice: 0% user + 0% kernel / faults: 2820 minor 274 major
      0.4% 5243/com.samsung.android.providers.context: 0.2% user + 0.1% kernel / faults: 1169 minor 57 major
      0.2% 5236/com.samsung.android.applock: 0.1% user + 0% kernel / faults: 1537 minor 170 major
      0.3% 3595/wificond: 0.1% user + 0.2% kernel
      0.1% 5320/android.process.acore: 0.1% user + 0% kernel / faults: 72 minor
      0% 3583/media.extractor: 0% user + 0% kernel / faults: 1022 minor 41 major
      0.2% 2591/kworker/u16:5: 0% user + 0.2% kernel
      0.2% 3435/android.hardware.bluetooth@1.0-service: 0.1% user + 0.1% kernel
      0.2% 12016/logcat: 0.1% user + 0.1% kernel
      0.1% 1//init: 0% user + 0.1% kernel / faults: 15 minor
      0% 5/kworker/0:0H: 0% user + 0% kernel
      0.1% 3441/android.hardware.graphics.composer@2.1-service: 0.1% user + 0% kernel
      0% 14304/com.myownpackage: 0% user + 0% kernel / faults: 68 minor 8 major
      0.1% 3447/android.hardware.wifi@1.0-service: 0% user + 0.1% kernel
      0% 3533/jbd2/dm-3-8: 0% user + 0% kernel
      0% 3569/zygote64: 0% user + 0% kernel / faults: 65 minor 4 major
      0% 3615/tombstoned: 0% user + 0% kernel / faults: 79 minor 50 major
      0.1% 9416/com.sec.spp.push: 0.1% user + 0% kernel / faults: 2 minor
      0.1% 13718/kworker/3:0: 0% user + 0.1% kernel
      0% 2589/kworker/7:1H: 0% user + 0% kernel
      0% 3458/surfaceflinger: 0% user + 0% kernel / faults: 73 minor 25 major
      0% 3570/zygote: 0% user + 0% kernel / faults: 56 minor 5 major
      0% 3573/audioserver: 0% user + 0% kernel / faults: 53 minor 15 major
      0% 3574/cameraserver: 0% user + 0% kernel / faults: 227 minor 106 major
      0% 3576/drmserver: 0% user + 0% kernel / faults: 198 minor 80 major
      0% 3589/mediaserver: 0% user + 0% kernel / faults: 120 minor 55 major
      0% 3591/remotedisplay: 0% user + 0% kernel / faults: 131 minor 51 major
      0% 3603/smdexe: 0% user + 0% kernel
      0% 4973/iod: 0% user + 0% kernel
      0% 5705/com.google.android.gms: 0% user + 0% kernel / faults: 5 minor
      0% 6003/kworker/2:2: 0% user + 0% kernel
      0% 10997/com.google.android.youtube: 0% user + 0% kernel / faults: 3 minor
      0% 11253/com.android.vending:instant_app_installer: 0% user + 0% kernel / faults: 7 minor
     +0% 14377/kworker/u16:3: 0% user + 0% kernel
     +0% 14386/kworker/u16:6: 0% user + 0% kernel
     +0% 14387/kworker/u16:8: 0% user + 0% kernel
    7.2% TOTAL: 3.3% user + 3.4% kernel + 0.3% iowait + 0% softirq
    CPU usage fro

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
