### ISSUE TITLE
Is there a purpose to have this line twice

### ISSUE THREAD

**Issue by hannesa2** [firebase/firebase-jobdispatcher-android#261]
.. or is it just senseless code duplicate ?

https://github.com/firebase/firebase-jobdispatcher-android/blob/e609dabf6cbd0fcc2451b8515f095cfbc3d9450a/.travis.yml#L33

**Comment by samtstern** [comment]
@hannesa2 this is a pretty common thing to see in Android `travis.yml` files, the context is here:
https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943

I don't know if the original bug still exists, but it doesn't hurt!
