### ISSUE TITLE
No support for Scheduling jobs at exact time

### ISSUE THREAD

**Issue by kpradeepkumarreddy** [firebase/firebase-jobdispatcher-android#265]
I want to schedule job at a particular time, instead of giving the execution window.

evernote's android-job library provides this feature. 

sample code to trigger exact jobs in evernote android-job library
 `int jobId = new JobRequest.Builder(DemoSyncJob.TAG)
            .setExact(20_000L)
            .build()
            .schedule(); `

Can you please add the same feature in firebaseJobDispatcher also ?

**Comment by myJarvis** [comment]
yes its not triggering jobs at exact time

**Comment by emailsubjekt** [comment]
That's your whole answer, not it will be fixed on a certain date, but yes it's happening, lol, I don't think I'll be using this job dispatcher, job scheduler didn't work either, it drained the battery immensely and it included a bunch of stuff I never need but this is a mockery. Can you please hire some experts to get this thing done right?

**Comment by emailsubjekt** [comment]
When can we expect all these issues to be fixed? I'd very much like to use your library but I can't due to all the unresolved issues.

**Comment by kpradeepkumarreddy** [comment]
You should be using WorkManager API.
WorkManagerApi is an replacement for FirebaseJobDispatcher API.  I think
FirebaseJobDispatcher is deprecated

**Comment by toddshansen** [comment]
closing as this will not be added to FJD given the deprecation.
