### ISSUE TITLE
How to force stop JobService from Activity

### ISSUE THREAD

**Issue by ashishkumawat** [firebase/firebase-jobdispatcher-android#271]
Not found any solution to stop service from activity like on click of button.

**Comment by kartubi** [comment]
same here -_-

**Comment by emailsubjekt** [comment]
I can't imagine these guys have so little idea what they're doing that they decided to not include a stop code anywhere. I mean, ok, you define it when you start it, but what if I wanted to finish it earlier? Not cool bro

**Comment by toddshansen** [comment]
ptal at these elements:
https://developer.android.com/guide/components/services#Lifecycle

and the example here: https://stackoverflow.com/questions/4748964/android-cancel-asynctask-forcefully

Both offer strategies to stop your service if you want.

Closing this as FJD is deprecated and so we won't be adding an additional api for this.
