### ISSUE TITLE
Not working when phone is idle

### ISSUE THREAD

**Issue by ghost** [firebase/firebase-jobdispatcher-android#272]
It working perfectly when app close, some time delay,it not a matter but 
job schedular not working when phone going to idle state

**Comment by arutkayb** [comment]
I checked the Battery Optimisation option on my phone options and see that my application is optimized by the phone. So, background services have been having problems with waking up. I set the "not optimize" option and see services are working fine.

**Comment by toddshansen** [comment]
FJD is one of the things deferred during doze mode. More info: https://developer.android.com/training/monitoring-device-state/doze-standby
