### ISSUE TITLE
Strange logs after device Android 9 update

### ISSUE THREAD

**Issue by EkslV** [firebase/firebase-jobdispatcher-android#277]
I get update android p for my xiaomi mi a1 with android one. And now in my app I get some strange logs:
` I/ActivityManager: Start proc 16145:com.myApp.id/u0a466 for service com.myApp.id/com.firebase.jobdispatcher.GooglePlayReceiver`
`I/NotificationService: Cannot find enqueued record for key: 0|com.myApp.id|43|null|10466`
`I/ActivityManager: Killing 16145:com.myApp.id/u0a466 (adj 906): empty #17`

If it something that I need to worry about? If it means that my job was canceled by new adaptive battery feature?

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
