### ISSUE TITLE
How to use multiple service in single class

### ISSUE THREAD

**Issue by yokikathir** [firebase/firebase-jobdispatcher-android#289]
this is my below code not working
if (myJob == null) {
            myJob = dispatcher.newJobBuilder()
                    // the JobService that will be called
                    .setService(ReminderService.class, OfflineceService.class)
                    // uniquely identifies the job
                    .setTag("my-unique-tag")
                    // one-off job
                    .setRecurring(true)
                    // don't persist past a device reboot
                    .setLifetime(Lifetime.FOREVER)
                    // start between 0 and 60 seconds from now
                    .setTrigger(Trigger.executionWindow(0, 1))
                    // don't overwrite an existing job with the same tag
                    .setReplaceCurrent(true)
                    // retry with exponential backoff
                    .setRetryStrategy(RetryStrategy.DEFAULT_EXPONENTIAL)
                    // constraints that need to be satisfied for the job to run
                    .setConstraints(
                            // only run on an unmetered network
                            Constraint.ON_ANY_NETWORK

                            // only run when the device is charging
                            // Constraint.DEVICE_CHARGING
                    )
                    .setExtras(myExtrasBundle)
                    .build();

            dispatcher.mustSchedule(myJob);
        }

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
