### ISSUE TITLE
Driver Docs

### ISSUE THREAD

**Issue by xXxXxXxXxXam** [firebase/firebase-jobdispatcher-android#29]
Could you provide more documentation about how to create custom Driver implementations? I'm trying to follow the GooglePlayDriver and it is hard to tell what is a requirement for this library and what is part of the GooglePlayDriver specific code.

It would be helpful to have a doc that says "To make a driver, you need to make sure it does xyz."

Thanks

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
