### ISSUE TITLE
Add JobScheduler-based Driver for L+, non-Google devices

### ISSUE THREAD

**Issue by yahor-makouski-epam** [firebase/firebase-jobdispatcher-android#32]
As long as Firebase JobDispatcher is a library that provides a high-level wrapper around job scheduling engines on Android I wonder whether it's possible to create a Driver implementation based on Lollipop's JobScheduler?

Firebase and Lollipop's schedulers require Job to extend from JobService and the problem is both schedulers provide their own abstract JobServices so I don't see a simple possibility to create one job and reuse it for different drivers.

**Comment by johan12345** [comment]
This is related to #24. As I said there, this library basically makes no sense as long as there is only one Driver implementation. However, as the last commit was 3 months ago, it seems that Google is currently not developing this library further.

**Comment by yahor-makouski-epam** [comment]
That's true, but I'm actually asking about possible ways of how to implement the Lollipop's Driver. It's clear to me how to implement Driver based on AlarmManager.

**Comment by johan12345** [comment]
Well, one would probably need to create a `android.app.job.JobService` in your `Driver` implementation that forwards calls to the `onStartJob` and `onStopJob` calls to the corresponding methods of the given `com.firebase.jobdispatcher.JobService` subclass.

**Comment by ciarand** [comment]
Hi folks, this is something I'm actively working on. It was always the intent of the library, we've just been occupied with some improvements to the scheduling engine inside Google Play services.

I'll have more to say on this topic next week.

**Comment by yahor-makouski-epam** [comment]
Hi @ciarand ! 
do you have any news regarding Driver for Lollipop's JobScheduler ?

**Comment by goncalossilva** [comment]
@ciarand Given work is underway, I assume contributions for a `JobScheduler` backed driver would be futile at this point. The `AlarmManager` backed one (#24) is harder, but is it safe to assume that no work has been put into it so far?

**Comment by alinberce** [comment]
@ciarand I was wondering what's the status on this? I keep hearing how recommended is to use added `JobSchedueler` here and there but there's no reason to use it because who only makes apps for androuiid21+? 

I've started to add this library to my project until I saw that it doesn't actually use the available `JobScheduler` within the android code, even if the android version has it. This means that for somebody who wants to keep things simple, AlarmManager remains the best option?

**Comment by zenyagami** [comment]
@ciarand thanks for the response, any update of this, i just came from Udacity training lessons and they recommend firebase, well i changed all my apps and i figure out they google play services , and some how is ok, but what about android 5.1+ that does not have Play services? the job scheduler should use the stock implementation right? for now im using if/else statements and kind of copy paste :s

**Comment by romainguefveneu** [comment]
Hi @ciarand! Any update on this?

**Comment by ciarand** [comment]
Sorry folks, this got put on the backburner and right now the team is focused on improving the performance of the Google Play services driver.

If someone is motivated we'd be happy to review PRs or help guide the design, but for the time being the team has no immediate plans to work on this for the next few quarters at least.

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
