### ISSUE TITLE
Could not get unknown property 'assembleRelease' for project

### ISSUE THREAD

**Issue by drmrbrewer** [firebase/firebase-jobdispatcher-android#33]
After updating Android Studio to version 2.2 and the gradle plugin to 2.2.0, I get following error:

> Error:(32, 1) A problem occurred evaluating project ':jobdispatcher'.
> Could not get unknown property 'assembleRelease' for project ':jobdispatcher' of type org.gradle.api.Project.

The problem is in the [build.gradle](https://github.com/firebase/firebase-jobdispatcher-android/blob/master/jobdispatcher/build.gradle) file of jobdispatcher (which I've imported into my project as a gradle module):

```
task aar(dependsOn: assembleRelease)
```

What changes can I make to fix this?

Note, this issue is very similar to, but still a bit different to, that reported [here](http://stackoverflow.com/q/39590549/4070848).

**Comment by drmrbrewer** [comment]
For answer, see [here](http://stackoverflow.com/a/39604659/4070848).

**Comment by vinaysshenoy** [comment]
Or, you can just run `./gradlew jobdispatcher:assembleRelease` and skip the pointless task. :-)

**Comment by SUPERCILEX** [comment]
This issue can be closed now since the library is provided through jCenter and mavenCentral.
