### ISSUE TITLE
Issues upgrading app to Play Services 9.6.x

### ISSUE THREAD

**Issue by nevi-me** [firebase/firebase-jobdispatcher-android#35]
I upgraded my app's Google Play Services dependency to 9.6.1, but I'm getting a RuntimeException when building the app. The issue is that there are duplicate `com.google.android.gms.gcmPendingCallback` classes. The first is from this library while the newer one is from 9.6.1.

Is it something that anyone has come across yet, and is there an alternate solution other than upgrading the jobdispatcher's dependency?

**Comment by LouisCAD** [comment]
I'd rename the problematic class in a clone of this repo, and then built it myself

**Comment by nevi-me** [comment]
Hey @LouisCAD I ended up sticking to 9.4 for now.

**Comment by ciarand** [comment]
This should be solved now. If you don't have a dependency on com.google.android.gms:play-services-gcm, you can use:

```groovy
compile 'com.firebase:firebase-jobdispatcher:0.5.0'
```

Otherwise you can use:

```groovy
compile 'com.firebase:firebase-jobdispatcher-with-gcm-dep:0.5.0'
```
