### ISSUE TITLE
Generate JavaDocs

### ISSUE THREAD

**Issue by tjohns** [firebase/firebase-jobdispatcher-android#36]
This project doesn't have any JavaDocs, which makes it very hard to navigate this project, and isn't in line with other Android/Google APIs.

JavaDocs should be generated and hosted on developer.google.com, firebase.google.com, or GitHub Pages.

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
