### ISSUE TITLE
How to schedule tasks that execute everyday(once)? Sorry if it is very basic.

### ISSUE THREAD

**Issue by rinikaravinth** [firebase/firebase-jobdispatcher-android#48]

**Comment by SUPERCILEX** [comment]
See https://github.com/firebase/firebase-jobdispatcher-android/pull/23/files.

**Comment by ocampoleandro** [comment]
Could you test it? Because I have set a task every 30 days and changing the system date / time doesn't help me to test it.

**Comment by blackhawk389** [comment]
What about if there is no tolerance interval I want to run job exactly specified time, in other words startwindow and endwindow are same?

**Comment by SUPERCILEX** [comment]
Use the [AlarmManager](https://developer.android.com/reference/android/app/AlarmManager.html) API.

**Comment by blackhawk389** [comment]
No its recurring like sending notification say every 4 minutes

**Comment by SUPERCILEX** [comment]
@blackhawk389 Google is your friend: https://developer.android.com/training/scheduling/alarms.html.

**Comment by blackhawk389** [comment]
I want to do it with job scheduler, it would be cumbersome with alarm manager(setting alarm every 4 minutes), have a look at this https://github.com/firebase/firebase-jobdispatcher-android/issues/131

**Comment by SUPERCILEX** [comment]
@blackhawk389 The point of job scheduler is for it to find the right time for the job.

**Comment by blackhawk389** [comment]
Didn't understand, could you elaborate

**Comment by FabianTerhorst** [comment]
When you for example want to execute an http request after the http request failed on the first try. You can configure the job scheduler to execute the job when an network connection is available. So you do not have to execute an job every 5 minutes to check the connection state.

**Comment by SUPERCILEX** [comment]
@blackhawk389 the job scheduler apis are intended for non time-based tasks. The idea is that you want some task to run with various constraints (internet connectivity, charging, not being used, etc.) in a reasonable time frame. You're looking for a task where time is the most important factor, not the other constraints.

**Comment by blackhawk389** [comment]
So what should I do, If Im using job scheduler it does not support devices running lower api level 21

**Comment by blackhawk389** [comment]
And could you provide information about set trigger, lets say I dont want to trigger job at exact time, lets say I relax condition that not exact time but after 1 or 2 minute, could I use trigger in this case

**Comment by samtstern** [comment]
I am cleaning up old issues so going to close this one.  It looks like @SUPERCILEX has answered this for the most part.  If you have a very time sensitive task you should use `AlarmManager`, which will execute at the specified time regardless of system conditions.  If you can afford flexibility, you can/should use `JobScheduler`.  However the key principle of `JobScheduler` is that it will decide when the best time to execute your job is.  You can't guarantee a delay of {x} minutes.
