### ISSUE TITLE
Kotlin: inaccessible constant Trigger.NOW

### ISSUE THREAD

**Issue by emce** [firebase/firebase-jobdispatcher-android#5]
I get this error trying to use library in Kotlin
`Type JobTrigger.ImmediateTrigger! is inaccessible in this context due to JobTrigger.ImmediateTrigger!`
![PrintScreen](http://images75.fotosik.pl/629/a3cb42a944877f1e.png)

**Comment by ciarand** [comment]
What version of Kotlin are you using?

**Comment by emce** [comment]
1.0.2

**Comment by sburba** [comment]
This issue is Trigger.NOW is of type ImmediateTrigger which is package private. Kotlin can't handle accessible objects with unaccessible types for some reason. Making Trigger.NOW of the more general type Trigger should fix it. Although I would argue this is more a bug with kotlin than this library.

**Comment by ciarand** [comment]
Thanks for the explanation @sburba. I'm going to follow up with the rest of the team this week, but it's likely we'll end up making the change you describe.

**Comment by sakebook** [comment]
Similar error.
I am also using the 1.0.2 of Kotlin.

![image](https://cloud.githubusercontent.com/assets/729101/15847752/6179aaac-2cc3-11e6-8b17-787148440505.png)

Trigger is not visible.

**Comment by chrisjenx** [comment]
I can understand the package/private constructor on those types. But package level class definitions is a bit weird, if you are going to do that, then return the generic type. 
I would argue that Kotlin actually handles this correctly, `Trigger` should be public and you return that instead of the package private types.

**Comment by JakeWharton** [comment]
> then return the public type... I would argue that Kotlin actually handles this better

Agree. And if you tried to define this in Kotlin it wouldn't actually compile. `javac` is being far too permissive here.

You can flag this as a fatal problem in IntelliJ/AS when developing:

<img width="977" alt="screen shot 2016-07-20 at 3 27 21 pm" src="https://cloud.githubusercontent.com/assets/66577/16999940/7c426dc8-4e8e-11e6-8b5c-5c5bf4aa3b95.png">

**Comment by stepango** [comment]
Same issue for me.

**Comment by outlying** [comment]
Same here

@ciarand could you make `JobTrigger` public and remove `Trigger` ?

I don't understand why we need `Trigger` class (seems like helper class), logic in `JobTrigger` and `Trigger` is plain simple, it could be merged and put in `JobTrigger` (with all argument checking, exceptions and `NOW` constant)

**Comment by nevi-me** [comment]
Does anyone have an interim solution other than forking and making the change for #43?

**Comment by outlying** [comment]
@nevi-me There is one https://github.com/outlying/card-check/blob/master/app/src/main/java/com/antyzero/cardcheck/TriggerConfigurator.java

**Comment by nevi-me** [comment]
great stuff @outlying, thanks!

**Comment by MGaetan89** [comment]
@outlying If you want to stay full-Kotlin, this workd too:

```kotlin
package com.firebase.jobdispatcher

class TriggerConfiguration {
    companion object {
        fun executionWindow(builder: Job.Builder, windowStart: Int, windowEnd: Int) {
            builder.trigger = Trigger.executionWindow(windowStart, windowEnd)
        }
    }
}
```

**Comment by ciarand** [comment]
Hey folks, v0.5.1 (available on JCenter) includes a fix for this.

**Comment by MGaetan89** [comment]
Thanks @ciarand
