### ISSUE TITLE
Scheduling a job that should run periodically but not before a certain time

### ISSUE THREAD

**Issue by michaeldiener** [firebase/firebase-jobdispatcher-android#52]
For example, I want to have a job, that runs every hour, but it should not start immediately, but tomorrow.

Currently it is only possible to have periodical jobs that would run the first time between now and trigger windowStart.

**Comment by Ansh1234** [comment]
Hi, instead of running a job periodically, you can run the job only once. The first once will be run after 24 hours(as per your requirement). Once the job is run, and the service is called, you can create the next job after 1 hour. Again this job is not periodic. When this job is run again, you can again decide when to run the next job i.e. after 1 hour or after 24 hours. 

I am also running periodic jobs in my application but instead of running a job periodically, I am running the job only once, and on the invoking of the job, I am scheduling the job again. This gives me more flexibility.

**Comment by michaeldiener** [comment]
Thanks, yes, I know there are workarounds for this, but this is more of a feature request. I worked with schedulers on other platforms and this was usually included.

**Comment by ciarand** [comment]
That's an interesting request. The way @Ansh1234 described is typically how we'd recommend users achieve this. Were you thinking a feature something like this?

```java
jobBuilder
  .setTrigger(Trigger.executionWindow(MINUTES.toSeconds(50), MINUTES.toSeconds(60)))
  .setInitialDelay(DAYS.toSeconds(1)) // <-- new
```

**Comment by michaeldiener** [comment]
Yes, exactly, something like this would be helpful in my use case!

**Comment by RotemShaanan** [comment]
@Ansh1234 Your idea sounds good, can you please show a code example?

**Comment by ngochuu90** [comment]
Cannot Resolve method ".setInitialDelay"

**Comment by chebTS** [comment]
I like the idea of adding something like this:
`.setInitialDelay(DAYS.toSeconds(1)) `
For instance, I need to do some task every day at 8:00 am. So I need to set initial delay(Next 8:00 AM - NOW), and then repeat this task every 24 hours.

**Comment by SlickSlime** [comment]
Is there currently any way to implement this solution till the time `.setInitialDelay()` feature is made available?

**Comment by unEgor** [comment]
You could schedule not repeated job at exact time you want your job to run. When the job started you can replace it with repeated job. The first job is just for initial delay.

**Comment by samyakjain** [comment]
+1 for setInitialDelay

**Comment by opannapo** [comment]
setInitialDelay() method please 😄

**Comment by mdkhere** [comment]
Can someone provide any Example for setInitialDelay()

**Comment by appleEyeBall** [comment]
@Ansh1234 How do you do that without calling setPeriodic()?

**Comment by bhuvaneshwariarkala** [comment]
i want to run the JobSchedular every day at 12am, how can I do that . Using JobInfo i did not find any option to set that.
Can someone provide info to do that?

**Comment by ashikazeez** [comment]
where is the method   .setInitialDelay(DAYS.toSeconds(1)) // <-- new

**Comment by rizwan49** [comment]
should we need to initialise FirebaseJobDispatcher in App level for periodic or we can write inside any activity , please suggest best approach to implement , I need to send analytics to server after certain time.

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
