### ISSUE TITLE
Not able to schedule job below Lollipop version and when Google play services is not installed.

### ISSUE THREAD

**Issue by Ansh1234** [firebase/firebase-jobdispatcher-android#54]
I am using firebase  job dispatcher using the dependency as follows. I have an explicit dependency on gcm

```
compile 'com.firebase:firebase-jobdispatcher-with-gcm-dep:0.5.0'.
compile "com.google.android.gms:play-services-gcm:8.4.0"
```

From the documentation it states that if the device is below Lollipop and Google Play services is not available, then it will use AlarmManager instead.

> 2: Uses AlarmManager to support API levels <= 21 if Google Play services is unavailable.

But in one of the devices which has Android version 4.2.2 and Google Play services 7.5.62, the job never runs. It should be invoked by AlarmManager according to the documentation.

**Comment by TrevorSStone** [comment]
That comment is referencing the evernote/android-job row of the table. Firebase jobdispatcher requires Google Play services on all API levels according to the docs.

**Comment by galvanu** [comment]
And if the device have not google play services installed than it won't work at all or use any API which doesn't requires Google play services?

**Comment by ciarand** [comment]
That's correct for the time being. We're working on implementing a JobScheduler driver (#32), but that's still pending.
