### ISSUE TITLE
Sleep Mode and Device Screen Off issues 

### ISSUE THREAD

**Issue by sharp-edge** [firebase/firebase-jobdispatcher-android#56]
So far its working fine until, I lock screen the device or let the device be inactive for a while.
As soon as I open the device lock, I see the My implementation of JobService getting called regardless of the Trigger 'windowStart' and 'windowEnd' time. If the device is Active then with some inconsistency in time the My JobService gets called.

Is this behavior normal ? Because I don't have battery saver turned On in the device.

`final static int periodicity = (int) TimeUnit.MINUTES.toSeconds(5);`
 `final static int toleranceInterval =  (int)TimeUnit.MINUTES.toSeconds(3);`

    Job myJob = dispatcher.newJobBuilder().setService(MyJobService.class)
                    .setTag("location-tag")
                    .setConstraints(

                        Constraint.ON_ANY_NETWORK)
                    .setTrigger(Trigger.executionWindow(periodicity, periodicity + toleranceInterval))
                    .setLifetime(Lifetime.FOREVER)
                    .setReplaceCurrent(true)
                    .build();

        int result = dispatcher.schedule(myJob);

        if(result != FirebaseJobDispatcher.SCHEDULE_RESULT_SUCCESS){
            Log.e("TAG", "Failed to schedule Job in JobDispatchingEntryPoint");
        }

Update: I've tested it on Lollipop only.

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
