### ISSUE TITLE
JobService not executed when specified to run in non default process

### ISSUE THREAD

**Issue by MartinNordh** [firebase/firebase-jobdispatcher-android#57]
Version: com.firebase:firebase-jobdispatcher:0.5.0
Android Version: 4.4.4

If the JobService is specified to execute on a different process.
Like:

 ```
<service
       android:exported="false"
       android:name="com.mydomain.myapp.MyJobService"
       android:process=":myprocess">
       <intent-filter>
           <action android:name="com.firebase.jobdispatcher.ACTION_EXECUTE"/>"
       </intent-filter>
   </service>
```

the JobService is not executed.

The following warning message is reported:
W/FJD.ExternalReceiver: Unknown service connected

Job Scheduling:

```
       
       final FirebaseJobDispatcher dispatcher = 
            new FirebaseJobDispatcher(new GooglePlayDriver(this));
        final Builder builder = dispatcher.newJobBuilder();
        builder.setService(MyJobService.class);
        builder.setTag(NOW_JOB_TAG);
        builder.setLifetime(Lifetime.UNTIL_NEXT_BOOT); 
        builder.setTrigger(Trigger.NOW);
        builder.setReplaceCurrent(true);
        builder.addConstraint(Constraint.ON_ANY_NETWORK);
        final Job job = builder.build();
        final int result = dispatcher.schedule(job);

```

**Comment by xozyain** [comment]
Have the same issue. If not same process, onStartJob won't be called at all.
Consider at least an error message in logcat?

**Comment by xozyain** [comment]
@MartinNordh  there's a simple solution. 
Override the manifest merger, by declaring the service "GooglePlayReceiver" with 
the process attribute:

```
<service
  android:name="com.firebase.jobdispatcher.GooglePlayReceiver"
  android:exported="true"
  android:process=":myprocess"
  android:permission="com.google.android.gms.permission.BIND_NETWORK_TASK_SERVICE">
  <intent-filter>
    <action android:name="com.google.android.gms.gcm.ACTION_TASK_READY" />
  </intent-filter>
</service>

<service
      android:exported="false"
      android:name="com.mydomain.myapp.MyJobService"
      android:process=":myprocess">
      <intent-filter>
          <action android:name="com.firebase.jobdispatcher.ACTION_EXECUTE"/>"
      </intent-filter>
  </service>

```

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
