### ISSUE TITLE
Constraint ON_ANY_NETWORK does not triggers when cellular network enabled for Android 4 

### ISSUE THREAD

**Issue by DmitriyYakovlev** [firebase/firebase-jobdispatcher-android#58]
Works fine on android 5 device for wifi and for cellular.
For device Lenovo a316i works only for wifi and does not triggers for cellular

version is :: 0.5.0

**Comment by samtstern** [comment]
@DmitriyYakovlev apologies that we never got around to responding to this.  As it's over a year old I am going to close it now (cleaning up issues).

In the future when you file issues please include as much information as you can.  Without some code and/or logs we really can't debug anything.
