### ISSUE TITLE
Question about job starting reliability

### ISSUE THREAD

**Issue by Kamil-Kaminski** [firebase/firebase-jobdispatcher-android#61]
Hi,

I have a problem with starting a job service. 
I have a following class:
```
public class JobsScheduler {

    private FirebaseJobDispatcher dispatcher;

    public JobsScheduler(Context context) {
        dispatcher = new FirebaseJobDispatcher(new GooglePlayDriver(context));
    }

    public void scheduleNetworkCheckJob(int startTime, int endTime) {
        Job myJob = dispatcher.newJobBuilder()
                .setService(NetworkCheckJobService.class)
                .setTag(NetworkCheckJobService.TAG)
                .setRecurring(false)
                .setLifetime(Lifetime.FOREVER)
                .setTrigger(Trigger.executionWindow(startTime, endTime))
                .setReplaceCurrent(true)
                .setRetryStrategy(RetryStrategy.DEFAULT_LINEAR)
                .build();

        dispatcher.mustSchedule(myJob);
    }
}
```
And I call `scheduleNetworkCheckJob` method with parameters 60 and 600 (1 and 10 minutes). And I have a problem with starting this job, because sometimes 10 minutes passed and job isn't called yet. 
Am I doing something wrong? 
I wanting following behaviour: I want this job to start after 1 minute and check if there is internet available or not, if no this job displays system notification.

Is there maybe any possibility to increase job priority, to start this after that 1 minute? Because sometimes it is called after 2 minutes, sometimes after 8 minutes, and sometimes it isn't called at all.

I have a Huawei P9 with Android M.

**Comment by kaiwalyakhasnis** [comment]
If you have very rigid constrain (i.e starting job exactly after 1 minute) then maybe it is good idea to implement this with AlarmManager

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
