### ISSUE TITLE
Is dispatcher a singleton object?

### ISSUE THREAD

**Issue by navidei** [firebase/firebase-jobdispatcher-android#62]
I want to know if I initialize the dispatcher in 2 components of my app are the dispatchers in sync? I mean does both of them have the jobs I have added in different parts?

**Comment by kaiwalyakhasnis** [comment]
No it is not signleton instance. Documentation(java doc) for FirebaseJobDispatcher says:
> Instantiates a new FirebaseJobDispatcher using the provided Driver.
https://github.com/firebase/firebase-jobdispatcher-android/blob/master/jobdispatcher/src/main/java/com/firebase/jobdispatcher/FirebaseJobDispatcher.java#L86

**Comment by navidei** [comment]
Thanks, So what's your suggestion if I want to access the dispatcher to for example cancel a job in a different part of my application?

**Comment by ciarand** [comment]
While the dispatcher isn't a traditional Java "singleton" – there's no static variables or anything – it uses a driver that talks to a shared datastore (Google Play services). If you schedule a job using one instance of the dispatcher, there's no reason you can't cancel with a second instance of the dispatcher.

I do recommend only instantiating one Dispatcher for performance / ease of testing reasons, but there's no hard requirement on that.
