### ISSUE TITLE
Is there anyway to schedule a job for a specific time?

### ISSUE THREAD

**Issue by navidei** [firebase/firebase-jobdispatcher-android#63]
Due to documentations I think the only way for achieving this, is to find the difference from now to the time I want the job to execute? Is it right or is there a better way for this demand?

**Comment by ciarand** [comment]
The way you described - finding the difference from now and the desired execution time - is the best way to meet that requirement.

Given that we can't guarantee any jobs will run by a certain point (that's dependent on whether the job's runtime constraints are satisfied, as well as how busy the system is), we've found this is the most effective way of expressing rough time constraints. Suggestions for improvements are always welcome.
