### ISSUE TITLE
What's differences between mustSchedule() and schedule() methods?

### ISSUE THREAD

**Issue by navidei** [firebase/firebase-jobdispatcher-android#64]

**Comment by kaiwalyakhasnis** [comment]
> **mustSchedule()**
> Attempts to schedule the provided Job, throws an exception if it fails. (**ScheduleFailedException**)

> **schedule()**
> Attempts to schedule the provided Job. Returns one of the (int value) SCHEDULE_RESULT_SUCCESS,
> SCHEDULE_RESULT_UNKNOWN_ERROR, SCHEDULE_RESULT_NO_DRIVER_AVAILABLE,
> SCHEDULE_RESULT_UNSUPPORTED_TRIGGER, SCHEDULE_RESULT_BAD_SERVICE

**Comment by ciarand** [comment]
Thanks @kaiwalyakhasnis. That's correct. mustSchedule returns void and throws an exception if the schedule request fails, whereas schedule() returns an int status code that indicates whether the request was successful.
