### ISSUE TITLE
Which thread runs my jobs ?

### ISSUE THREAD

**Issue by Zeyad-37** [firebase/firebase-jobdispatcher-android#65]
On which thread do my jobs run? and is it safe to run long tasks there or should i start an Intent Service ?

**Comment by kaiwalyakhasnis** [comment]
Documentation for JobService says:

> Users will need to override {@link #onStartJob(JobParameters)}, which is where any asynchronous
 > execution should start. This method, like most lifecycle methods, runs on the **main thread;** you
 > <b>must</b> offload execution to another thread (or {@link android.os.AsyncTask}, or
 > {@link android.os.Handler}, or your favorite flavor of concurrency).

You can use SimpleJobService 
 > SimpleJobService provides a simple way of doing background work in a JobService.
 > Users should override onRunJob and return one of the {@link JobResult} ints.

**Comment by Zeyad-37** [comment]
Thanks  for your response. It very helpful. but just fyi, none of the links you made work.
