### ISSUE TITLE
Sync artifacts with Maven Central in addition to JCenter

### ISSUE THREAD

**Issue by ciarand** [firebase/firebase-jobdispatcher-android#68]
Pointed out by @gabrielittner in #1.

**Comment by samtstern** [comment]
@ciarand I would suggest closing this as obsolete.  If you want to support a non-Jcenter maven repo it should probably be maven.google.com but even that is not necessary.  jCenter is the Android standard and there is no use for this library outside of Android.

If folks are using some build system and really need a maven repo URL they can use this:
https://dl.bintray.com/firebase/firebase-jobdispatcher/

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
