### ISSUE TITLE
Add a getAllPendingJobs() method

### ISSUE THREAD

**Issue by ciarand** [firebase/firebase-jobdispatcher-android#69]
This should roughly match the behavior of the JobScheduler's version: https://developer.android.com/reference/android/app/job/JobScheduler.html#getAllPendingJobs()

**Comment by longinoa** [comment]
@ciarand How can you do this if `GcmNetworkManager` doesn't expose this as an API?

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
