### ISSUE TITLE
Failed to resolve com.firebase:firebase-job dispatcher-with-gcm-dep:0.5.2

### ISSUE THREAD

**Issue by ymane** [firebase/firebase-jobdispatcher-android#78]
Android project build error

**Comment by googolmo** [comment]
There is no 0.5.2 in `http://jcenter.bintray.com/com/firebase/firebase-jobdispatcher-with-gcm-dep/`

**Comment by yogeshpatil143** [comment]
compile 'com.firebase:firebase-jobdispatcher:0.5.2'

Add below line and compile grable

Problem solve

**Comment by krupalbhardiya** [comment]
implementation 'com.firebase:firebase-jobdispatcher:0.8.5'

Gradle sync error: 
Failed to resolve: com.firebase:firebase-jobdispatcher:0.8.5

**Comment by Igalsr** [comment]
Although the documentation says 0.8.5 Change to 0.8.4 it worked for me

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
