### ISSUE TITLE
GooglePlayDriver limitations?

### ISSUE THREAD

**Issue by ScottPierce** [firebase/firebase-jobdispatcher-android#82]
Is the Firebase JobDispatcher subject to the same limitations of the GcmNetworkManager when using the GooglePlayDriver?

For instance, the GcmNetworkManager documentation says that on Google Play Services update, all the jobs are deleted. It then gives us the `onInitializeTasks()` method to re-instantiate those scheduled tasks. Is the same thing going to happen with the Firebase JobDispatcher, and if so, do we have access to a callback to re-create the jobs?

**Comment by sytolk** [comment]
I think it`s have the same issues:
https://github.com/firebase/firebase-jobdispatcher-android/issues/6

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
