### ISSUE TITLE
Job scheduled with Trigger.NOW doesn't run immediately

### ISSUE THREAD

**Issue by doudasek** [firebase/firebase-jobdispatcher-android#83]
I have class which extends `JobService` and in some cases I need to run it as soon as possible. If I plan new `Job` with **no constraint** and trigger set to `Trigger.NOW`, I expect that the service will be started immediatelly. As documentation says: 

> Immediate is a Trigger that's immediately available. The Job will be run as soon as the runtime constraints are satisfied.

It usually takes about 1 minute to start the service (the app is in foreground, no idle state). Is it OK? Is there way how to manually start the service immediately? 

The code for planning:
```
FirebaseJobDispatcher dispatcher = new FirebaseJobDispatcher(new GooglePlayDriver(context.getApplicationContext()));
Job job = dispatcher.newJobBuilder()
                .setService(MyService.class)
                .setTag(TAG_SERVICE) 
                .setRecurring(false)
                .setTrigger(Trigger.NOW)
                .build();
dispatcher.mustSchedule(job);
```

Thank you, 
Martin

**Comment by SUPERCILEX** [comment]
This is normal, it's like the native job scheduler api. You tell when you would like your background task to be executed, but the scheduler decides.

See documentation: https://github.com/firebase/firebase-jobdispatcher-android/blob/master/jobdispatcher/src/main/java/com/firebase/jobdispatcher/JobTrigger.java#L29
> The scheduler backend is encouraged to use the windowEnd value as a signal that the job should be run, but this is not an enforced behavior.

**Comment by HenningBu** [comment]
> Is it OK? Is there way how to manually start the service immediately?

I've made good experiences with:
`Trigger.executionWindow(0, 0)` instead of `Trigger.NOW`

**Comment by doudasek** [comment]
@HenningBu Thank you very much! `Trigger.NOW` takes about 1 minute, `Trigger.executionWindow(0, 0)` takes about 50ms.

**Comment by s3r6** [comment]
@SUPERCILEX If windowEnd is not enforced so when the task will be run in the worst case? Which is the latest timeout?

**Comment by unEgor** [comment]
FJD does not have strict timeout or deadline.
The job will be executed only if all constrains are satisfied even if it is expired.

We are working on faster execution. So a job with ImmediateTrigger will be executed immediately.

**Comment by s3r6** [comment]
How can I debug what scheduler is waiting for? There is simple case from example, but it runs once and delays about 5 minutes sometimes.
```java
Job myJob = dispatcher.newJobBuilder()
    .setService(MyService.class)
    .setRecurring(true)
    .setTrigger(Trigger.executionWindow(10, 20))
    .setTag("job-tag")
    .build();
```

**Comment by unEgor** [comment]
You can check task status by running "adb shell dumpsys activity service GcmService"

**Comment by Kethu-Yerramma** [comment]
Here is the code for running Firebasedispatcher Jobservice 

Driver driver = new GooglePlayDriver(SampleActivity.this);
        firebaseJobDispatcher = new FirebaseJobDispatcher(driver);

        Job job = firebaseJobDispatcher.newJobBuilder()
                .setService(JobServiceTrial.class)
                .setTrigger(Trigger.executionWindow(0,0)/*executionWindow(0, 0)*/)
                .setTag("TAG") //identifier for the job
                .setRecurring(false) // should not recur
                // should persist device reboot
                .setReplaceCurrent(false) // no need to replace previous job
                .setConstraints(Constraint.ON_ANY_NETWORK) // set network availability constraint
                .setRetryStrategy(RetryStrategy.DEFAULT_EXPONENTIAL)
                .build();

1.After calling this only onStart is calling.onStop won't called.If I call again above code then onstop,onStart.For every click it'll be repeated.

**Comment by Kethu-Yerramma** [comment]
Please help to fix it.

**Comment by lordplagus02** [comment]
Still a little "screwy" in terms of execution window, whether it's `.setTrigger(Trigger.executionWindow(0,0))` or `.setTrigger(Trigger.NOW)` which causes some confusion if you're using firebase jobs to run sync code (to fetch data from server etc). If it started 10-20 seconds late would be fine, but it's so erratic...

**Comment by lordplagus02** [comment]
I've just noticed that jobs scheduled to start immediately won't start unless the app is in the background, while I'm plugged into the debugger, not sure if it's happening when disconnected.
