### ISSUE TITLE
Job Dispatcher should depend on individual v4 Support Libraries

### ISSUE THREAD

**Issue by ianhanniballake** [firebase/firebase-jobdispatcher-android#85]
As per [v4 Support Libraries](https://developer.android.com/topic/libraries/support-library/packages.html#v4), version 24.2.0 split the monolithic Support Library into separate libraries, allowing developers to only use the pieces they need.

Right now, `com.firebase:firebase-jobdispatcher:0.5.2` depends on the entire `com.android.support:support-v4:25.0.0` (even though I doubt it actually requires `media-compat`). This causes issues when combined with libraries that only depend on the separate libraries.

For example, using:

```
dependencies {
    compile "com.firebase:firebase-jobdispatcher:0.5.2"
    compile "com.android.support:customtabs:25.1.0"
}
```

Leads to a Lint error:

> All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 25.1.0, 25.0.0. Examples include com.android.support:customtabs:25.1.0 and com.android.support:support-core-ui:25.0.0

As `customtabs:25.1.0` pulls in only `support-compat:25.1.0`, not the entirety of `support-v4:25.1.0`.

**Comment by kylefowler** [comment]
Outisde of the usage of SimpleArrayMap is the support library really needed? It would be great to remove that dependency as a whole.

**Comment by ianhanniballake** [comment]
Kind of moot point since Firebase JobDispatcher depends on Google Play services, which depends on Support Library.

**Comment by kylefowler** [comment]
Valid. I didn't know that about play services.

**Comment by ianhanniballake** [comment]
Looks like now the dependency should be changed to only be `support-compat` as the other libraries are not used.
