### ISSUE TITLE
Device Idle state constraint cannot be set

### ISSUE THREAD

**Issue by Arjun-sna** [firebase/firebase-jobdispatcher-android#86]
Not able to set device idle state constraint. I mean there is no configuration equivalent to `setRequiresDeviceIdle(boolean requiresDeviceIdle)`. Available constraints are `Constraint.ON_ANY_NETWORK` `Constraint.DEVICE_CHARGING` `Constraint.ON_UMMETERED_NETWORK`

**Comment by stevesamknows** [comment]
Would also find this feature useful.  We run core features periodically in the background, and
those are persisted across device reboots -- but we don't want the background job to run when
the app is active in the foreground (resource contention skews result metrics etc).  By simply
having the ability to specify that the device needs to be idle, we prevent the conflict without
having to jump through hoops to try to cancel one or the other of the (foreground/background) jobs (or check state with all the attendant opportunities to introduce bugs) in different threads or worry about accidentally cancelling the background job persistence across reboots.  In short, a very useful flag to easily provide a safe and extremely simple way to force either/or on the fg/bg job.

**Comment by louistsaitszho** [comment]
I know I am super late, but now there is `Constraint.DEVICE_IDLE`. Whoever maintain this might want to close this.
