### ISSUE TITLE
Scheduled jobs are lost after device switch off

### ISSUE THREAD

**Issue by bkjbkjbnkj687698698** [firebase/firebase-jobdispatcher-android#87]
I have scheduled some jobs and its working fine if i keep the device switch on.But if i switch off my device then after switching on the scheduled jobs doesn't execute?Below is the code i m using-

>  Job myJob = dispatcher.newJobBuilder()
>                         .setService(MyJobService.class)
>                         .setTag("DataSend")
>                         .setRecurring(false)
>                         .setLifetime(Lifetime.FOREVER)
>                         .setTrigger(Trigger.executionWindow(0, 0))
>                         .setRetryStrategy(RetryStrategy.DEFAULT_EXPONENTIAL)
>                         .setConstraints(Constraint.ON_ANY_NETWORK)
>                         .setExtras(myExtrasBundle)
>                         .build();

**Comment by henriquemelissopoulos** [comment]
Maybe you have the same issue I had, try what I did at: #90

**Comment by jayanthb94** [comment]
I had the same issue. I got it to work after adding `RECEIVE_BOOT_COMPLETED` permission in the manifest file.

**Comment by yishai-glide** [comment]
@jayanthb94 same here, but the whole point of using this is not to use additional permissions and get this from the system/library

**Comment by jeetnegi** [comment]
its working fine in my case 
`  dispatcher = new FirebaseJobDispatcher(new GooglePlayDriver(getApplicationContext()));

        Job myJob = dispatcher.newJobBuilder()
                // the JobService that will be called
                .setService(MyJobService.class)
                // uniquely identifies the job
                .setTag("my-unique-tag")
                // one-off job
                .setRecurring(true)
                // don't persist past a device reboot
                .setLifetime(Lifetime.FOREVER | Lifetime.UNTIL_NEXT_BOOT)
                // start between 0 and 60 seconds from now
                .setTrigger(Trigger.executionWindow(0, 60))
                // don't overwrite an existing job with the same tag
                .setReplaceCurrent(false)
                // retry with exponential backoff
                .setRetryStrategy(RetryStrategy.DEFAULT_LINEAR)
                // constraints that need to be satisfied for the job to run
                .setConstraints(
                        // only run on an unmetered network
                        Constraint.ON_ANY_NETWORK
                )
                .build();

        dispatcher.mustSchedule(myJob);`

**Comment by samtstern** [comment]
Going to move the discussion here to #101, which has a more active thread and a lot of the same questions.

**Comment by EdwinaVargas** [comment]
me funcionó colocando

**.setRecurring(false)
.setTrigger(Trigger.NOW)**

además de colocar  **<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>**  en el archivo de manifiesto
