### ISSUE TITLE
Scheduled jobs are not working when app is close 

### ISSUE THREAD

**Issue by ymane** [firebase/firebase-jobdispatcher-android#88]
Scheduled jobs are not working when app is close working only when app is open

**Comment by henriquemelissopoulos** [comment]
Maybe you have the same issue I had, try what I did at: #90

**Comment by arutkayb** [comment]
I checked the Battery Optimisation option on my phone options and see that my application is optimized by the phone. So, background services have been having problems with waking up. I set the "not optimize" option and see services are working fine.

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
