### ISSUE TITLE
Job never start after boot with Trigger.executionWindow(0, 0) and Lifetime.FOREVER combined

### ISSUE THREAD

**Issue by henriquemelissopoulos** [firebase/firebase-jobdispatcher-android#90]
I tried to upload pictures with the following setting

        Job job = dispatcher.newJobBuilder()
                .setService(UploadJobService.class)
                .setTag("picture-item-" + itemId)
                .setConstraints(Constraint.ON_ANY_NETWORK)
                .setRetryStrategy(RetryStrategy.DEFAULT_EXPONENTIAL)
                .setLifetime(Lifetime.FOREVER)
                .setReplaceCurrent(true)
                .setExtras(bundle)
                .setTrigger(Trigger.executionWindow(0, 0))
                .build();

But the job never start after a reboot, I think the problem is defining the executionWindow(0, 0).

It was hard to understand what was going on because even removing the executionWindow(0, 0) didn't make my job work again. Needed to remove the executionWindow(0, 0) and also change the TAG. Now the previous tag is lost in a limbo that even setReplaceCurrent(true) and dispatcher.cancelAll() can't clean!

**Comment by meidikawardana** [comment]
#101

**Comment by ebnrdwan** [comment]
what i see is your start and end times is equal inn the executionWindow(0,0), end time has to be larger than the start, otherwise i see that your are good to go

**Comment by prashantsinghpaliwal** [comment]
Only problem with your code is that you have provided literally no window for execution of the job. The end time has to be larger than the start time. It helps in picking up the best time to start the job reducing battery drain and hence enhancing performance. HAppy users!!

**Comment by faraztanveer24** [comment]
Please somebody explain what setTrigger(Trigger.executionWindow(0, 0))
actually do?
Please also explain other methods used in above written code

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
