### ISSUE TITLE
Scheduling a job to run from 8pm to 11pm

### ISSUE THREAD

**Issue by javimar** [firebase/firebase-jobdispatcher-android#93]
Hi, I have been trying to make the job to run only in non-asleep hours.  I have something like this but I would like to insert the time constraint in the title.

`.newJobBuilder

                .setConstraints(Constraint.DEVICE_CHARGING)
                .setLifetime(Lifetime.FOREVER)
                .setRecurring(true)
                .setTrigger(Trigger.executionWindow(
                        REMINDER_INTERVAL_SECONDS,
                        REMINDER_INTERVAL_SECONDS + SYNCH_FLEXTIME_SECONDS))
                .setReplaceCurrent(true)
                .build();
`

I have seen other issues related to this topic but so far I haven't seen the answer. Is this possible with FJD?

Thanks!

**Comment by hi-manshu** [comment]
Actually you can trigger from 8 to 11.

**Comment by tuckercr** [comment]
One option might be
- Use AlarmManager to set an inexact alarm for some time before 8PM
- When the alarm is received, then you schedule a job in the windows of X to Y minutes where X is the number of minutes until 8pm, and Y is the end of your execution window.

Of course this assumes that the job you want ran between 8-11PM requires a lot of resources and/or you need to make use of Constraints and so on.  If you job is less resource intensive you may as well just run it when the original alarm is received.

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
