### ISSUE TITLE
Service not work on disabled screen

### ISSUE THREAD

**Issue by ATumbler** [firebase/firebase-jobdispatcher-android#99]
I use FJD + Volley for connect with server every minute. Service dont work when screen off!

    public class NotificationJobService extends JobService
{
SharedPreferences pref;
SharedPreferences.Editor editor;
@Override
public boolean onStartJob(JobParameters job)
{
    pref = getApplicationContext().getSharedPreferences("settings", Context.MODE_PRIVATE);
    editor = pref.edit();
	String url = SomeClass.BASE_URL;
	Response.Listener<String> responseSuccess = new Response.Listener<String>(){
		@Override
		public void onResponse(String response)
		{
			if(!response.endsWith("ь")) {
				int serverId = Integer.parseInt(response);
                int prefId = getLastPrefId();
                if (prefId == 0) prefId = serverId;
                if (serverId > prefId)
                {
                    showNotification();
                }
                    setLastPrefId(serverId);
            }
		}
	};
	
	Response.ErrorListener responseFailed = new Response.ErrorListener(){

		@Override
		public void onErrorResponse(VolleyError error)
		{
			
		}
	};
	
	StringRequest request = new StringRequest(Request.Method.POST, url, responseSuccess, responseFailed){
		@Override
        protected Map<String, String> getParams()
        {
            Map<String, String> params = new HashMap<String, String>();
            params.put("login", pref.getString("address", ""));
			params.put("password", pref.getString("key", ""));
			params.put("get", "lastid");
            return params;
        }
	};
	VolleyApplication.getInstance().getRequestQueue().add(request);
	return false;
}

@Override
public boolean onStopJob(JobParameters job)
{
    return true;
}

public int getLastPrefId()
{ return pref.getInt("lastid", 0); }

public void setLastPrefId(int pref)
{
	editor.putInt("lastid", pref);
	editor.commit();
}

public void showNotification()
{
	NotificationCompat.Builder mBuilder = new NotificationCompat.Builder(this)
		.setSmallIcon(R.drawable.ic_launcher)
		.setContentTitle("Wow!")
		.setContentText("Open app")
		.setSound(RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION))
		.setAutoCancel(true);
	Intent intent = new Intent(this, MainActivity.class);
	PendingIntent pi = PendingIntent.getActivity(this, 0, intent, PendingIntent.FLAG_UPDATE_CURRENT);
	mBuilder.setContentIntent(pi);
	NotificationManager mNotificationManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
	mNotificationManager.notify(0, mBuilder.build());
}
    }

Create service and run

    FirebaseJobDispatcher dispatcher = new FirebaseJobDispatcher(new GooglePlayDriver(context));
Job myJob = dispatcher.newJobBuilder()
.setService(NotificationJobService.class)
.setTag("request")
.setRecurring(true)
.setLifetime(Lifetime.FOREVER)
.setTrigger(Trigger.executionWindow(0, 60))
.setReplaceCurrent(false)
.setRetryStrategy(RetryStrategy.DEFAULT_EXPONENTIAL)
.setConstraints(Constraint.ON_ANY_NETWORK)
.build();

	dispatcher.schedule(myJob);

**Comment by diegomontoya** [comment]
GCM scheduler will only at best call your job every 15 minutes in dooze mode and actual value is much higher than that.

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
